### ISSUE TITLE
Populate detail page for a dataset

### ISSUE THREAD

**Issue by seanprivett** [ministryofjustice/find-moj-data#102]
https://www.figma.com/file/zTOVhHRnWfxRJqH6Gr8cIc/Catalogue-sketches?type=design&node-id=203-2121&mode=design&t=dPhpPvOMFrw2s7e8-0

Python library:
- [x] Fetch dataset with schema

Template:

- [x] Grey box
- [x] Contact info
- [x] Schema

Resource section I'm gonna assume is another ticket

**Comment by MatMoore** [comment]
https://github.com/ministryofjustice/find-moj-data/pull/136

**Comment by MatMoore** [comment]
Initial PR merged, moving onto the metadata displayed at the top of the template

**Comment by MatMoore** [comment]
Highlighted the gaps between the design and current prototype here
https://miro.com/app/board/uXjVN8HvsEU=/?moveToWidget=3458764582047298000&cot=14

Some of them should be straightforward, some I will move out into separate tickets. TBD with Alex first

**Comment by MatMoore** [comment]
This can be considered done.

I've identified some follow up work which can be picked up as separate tickets:

https://github.com/ministryofjustice/data-platform/pull/3722
https://github.com/ministryofjustice/find-moj-data/issues/178
https://github.com/ministryofjustice/data-platform/issues/3723
https://github.com/ministryofjustice/data-platform/issues/3724
https://github.com/ministryofjustice/data-platform/issues/3725
https://github.com/ministryofjustice/data-platform/issues/3727
