### ISSUE TITLE
Interactions in user guide

### ISSUE THREAD

**Issue by YvanMOJdigital** [ministryofjustice/find-moj-data#1050]
make it like: https://guidance.data.gov.uk/publish_and_manage_data/

**Comment by MatMoore** [comment]
The config file for the above site is here: https://github.com/alphagov/datagovuk-tech-docs/blob/main/config/tech-docs.yml

- I think the most important setting we are missing is [multipage_nav](https://matmoore.github.io/tdt-documentation/configure_project/global_configuration/index.html#multipage-nav).
- We can also enable [collapsible_nav](https://matmoore.github.io/tdt-documentation/configure_project/global_configuration/index.html#collapsible-nav) - without it the nav will be fully expanded all the time.
- [max-toc-heading-level](https://matmoore.github.io/tdt-documentation/configure_project/global_configuration/index.html#max-toc-heading-level) can also be used to limit the number of levels shown

The nav tree should match up with the directory structure.
