### ISSUE TITLE
Front end designs for registration

### ISSUE THREAD

**Issue by seanprivett** [ministryofjustice/find-moj-data#106]
https://www.figma.com/file/zTOVhHRnWfxRJqH6Gr8cIc/Catalogue-sketches?type=design&node-id=14-439&mode=design&t=dPhpPvOMFrw2s7e8-0

end to end registration process in Figma
consider a flexible, generic pathway that can accommodate first time registration and also maintenance - coming back to update entries.
how do we include better contextual guidance while registering
what about the idea of breaking down the big freeform description field into a template that directs users to enter specific bits of information
if possible sketch out how a gateway process might work

**Comment by alex-vonfeldmann** [comment]
@seanprivett what is a 'gateway' process?
