### ISSUE TITLE
Evaluate Subject Area structure and recommend improvements

### ISSUE THREAD

**Issue by LavMatt** [ministryofjustice/find-moj-data#1065]
### User Story

As a user of find moj data
I expect to have comprehensive coverage of subject areas, with all data mapping to a subject area
So that i can browse all available data via the subject area route

### Value / Purpose

We currently have gaps in our subject areas becoming more apparent as we are bringing in data from more areas after the initial ingestion of create-a-derived-table datasets. 

This is because we have, up until now, created domains to mirror the structure of cadet. This is becoming unfit for purpose as we ingest more metadata.

There are two main issues with the current structure:
1. We have no way to effectively assign broader reaching data to a subject area, e.g. data that covers both prisons and probation or courts and tribunals.
2. Where data for an area don't exist at all in cadet, in some cases we have no domain to assign data from other sources. e.g. Legal Aid Agency and re-offending data.

The structure should aim to cover the majority of gaps, addressing the issues above.

We should consider bringing back the initial domain/subdomain structure we had before the current one as it is not possible to assign data to more than one domain in datahub (and domain maps to subject area in find-moj-data)

### Proposal

To generate an improved subject area structure to share with interested parties (initially DIP and DMET) and gain an agreement for implementation.

We should explore and document options to better assist the discoverability of data via subject areas:

potentially:
1. exploring a different set of domains and intrducintg a tiered approach where domains could be inclusive of sub-domains, e.g HMPPS >> [Prisons, Probation]
2. Have a flat list of domains which are more broad than the current set, and then use tags to  set a more specific subject area for each entity.

Once agreed we'll need to think about the plan for technical implementation (a separate issue)and likely moving away from cadet being the source of domains.

### Definition of Done

- [x] Generate options for new and improved subject area structure
- [x] Agree approach with the internal team
- [ ] Setup meeting to present and agree with wider interested parties

**Comment by MatMoore** [comment]
Previous taxonomy with subdomains: https://github.com/ministryofjustice/find-moj-data/pull/99/files

**Comment by MatMoore** [comment]
These are the GOV.UK subject areas in use by statistical publications

- Crime Justice and Law
  - Justice system transparency
  - Prisons and probation
    - Multi-agency public protection arrangements (MAPPA)  
  - Legal aid
  - Reoffending and rehabilitation
  - Family justice system
  - Courts, sentencing, and tribunals
  - Criminal justice reform
  - Victims of crime
  - Legal aid reform
  - Policing

The full list of subject areas within Crime Justice and Law:

- [Administrative justice reform](https://www.gov.uk/crime-justice-and-law/administrative-justice-reform)
- [Attorney General guidance to the legal profession](https://www.gov.uk/crime-justice-and-law/attorney-general-guidance-to-legal-profession)
- [Byelaws](https://www.gov.uk/crime-justice-and-law/byelaws)
- [Civil justice reform](https://www.gov.uk/crime-justice-and-law/civil-justice-reform)
- [Counter-extremism](https://www.gov.uk/crime-justice-and-law/counter-extremism)
- [Counter-terrorism](https://www.gov.uk/crime-justice-and-law/counter-terrorism)
- [Courts, sentencing and tribunals](https://www.gov.uk/crime-justice-and-law/courts-sentencing-tribunals)
- [Crime prevention](https://www.gov.uk/crime-justice-and-law/crime-prevention)
- [Criminal justice reform](https://www.gov.uk/crime-justice-and-law/criminal-justice-reform)
- [Criminal record disclosure](https://www.gov.uk/crime-justice-and-law/criminal-record-disclosure)
- [Data protection](https://www.gov.uk/crime-justice-and-law/data-protection)
- [Domestic abuse](https://www.gov.uk/crime-justice-and-law/domestic-abuse)
- [Family justice system](https://www.gov.uk/crime-justice-and-law/family-justice-system)
- [Forced marriage](https://www.gov.uk/crime-justice-and-law/forced-marriage)
- [Justice system transparency](https://www.gov.uk/crime-justice-and-law/justice-system-transparency)
- [Knife, gun and gang crime](https://www.gov.uk/crime-justice-and-law/knife-gun-and-gang-crime)
- [Law and practice](https://www.gov.uk/crime-justice-and-law/law-practice)
- [Legal aid](https://www.gov.uk/crime-justice-and-law/legal-aid-for-providers)
- [Legal aid reform](https://www.gov.uk/crime-justice-and-law/legal-aid-reform)
- [Policing](https://www.gov.uk/crime-justice-and-law/policing)
- [Prisons and probation](https://www.gov.uk/crime-justice-and-law/prisons-probation)
- [Reoffending and rehabilitation](https://www.gov.uk/crime-justice-and-law/reoffending-and-rehabilitation)
- [Reporting crimes and getting compensation](https://www.gov.uk/crime-justice-and-law/reporting-crimes-compensation)
- [Sentencing reform](https://www.gov.uk/crime-justice-and-law/sentencing-reform)
- [Statutory rights](https://www.gov.uk/crime-justice-and-law/statutory-rights)
- [Victims of crime](https://www.gov.uk/crime-justice-and-law/victims-of-crime)
- [Violence against women and girls](https://www.gov.uk/crime-justice-and-law/violence-against-women-and-girls)
- [Young people and the law](https://www.gov.uk/crime-justice-and-law/young-people-and-the-law)
- [Your rights and the law](https://www.gov.uk/crime-justice-and-law/rights)

**Comment by MatMoore** [comment]
Justice data breaks up legal aid like this

- [Legal aid data](https://data.justice.gov.uk/legalaid)
  - [Crime lower](https://data.justice.gov.uk/legalaid/legal-aid-crime-lower)
  - [Crime higher](https://data.justice.gov.uk/legalaid/legal-aid-crime-higher)
  - [Legal help](https://data.justice.gov.uk/legalaid/legal-aid-help-controlled-representation)
  - [Civil representation](https://data.justice.gov.uk/legalaid/legal-aid-civil-representation)
  - [Mediation](https://data.justice.gov.uk/legalaid/legal-aid-mediation)
  - [Exceptional case funding](https://data.justice.gov.uk/legalaid/legal-aid-ecf)


Quick review of what's in general now

- Lots of legal aid stuff
- common_lookup tables
- lookup tables specific to the criminal justice system (HO offense codes)
- common dimension tables (bank holidays)
- Contracts stuff
- Property lookups
- Population data
- Various charts related to crime and the courts
- Probation stuff
- Data about solicitors
- Greening Government Commitments
- Youth custody service (distinct part of HMPPS)

There still seems like a need for some kind of general category containing lookup data, population statistics, common dimensions etc. but it should be better named and not cluttered with uncategorised data.

Adding a legal aid subject area back in is a no brainer.

Greening government commitments data feels like it belongs in a HQ/corporate subject area.

**Comment by MatMoore** [comment]
Slide deck with options/recommendations - https://justiceuk.sharepoint.com/:p:/r/sites/DataCatalogue/Shared%20Documents/Show%20%26%20Tells/Find%20MoJ%20data%20subject%20area%20taxonomy%20update%20-%20Dec%202024.pptx?d=wac2ac8afa0954ee286d7ac87906808db&csf=1&web=1&e=PelSf6

I still need to work through how we would practically migrate to the new approach.

**Comment by MatMoore** [comment]
## Agreed approach

We can split the problem into two:

1. The categorisation system is too inflexible
2. The subject areas themselves need improving

To address 1, we are proposing to ditch datahub domains and use tags instead. We will start by reimplementing the current design using tags (e.g. we will set tags for the subject area when ingesting, and we will filter by tag instead of domain when searching). We will need another spike for this to prove it is technically feasible. 

Once we have switched to this system, we can introduce subtopics as additional tags, allowing users to click on a broad subject area, see results, then refine their search further. Mock this up for the slide deck.

Before closing this ticket, check if there is additional metadata we can associate with a tag besides its name. We are wondering if we need to store which tags are subject area tags in a YAML file, or if we can fetch this from Datahub.

I'll produce a smaller slide deck covering this part which we can show to stakeholders. 

To address 2, I'll do one more pass over the proposed subject areas based on team feedback, then we will do some user research to validate these.

**Comment by MatMoore** [comment]
Documentation for the tag entity in Datahub: https://datahubproject.io/docs/generated/metamodel/entities/tag

- You can give it an owner
- You can give it a colour

We could use the colour to improve usability within Datahub but it doesn't look like we can bring back all tags with a certain colour or anything like that.

It looks like it would be easiest to query *all* the tags, and then filter the list in Find MoJ data as appropriate. We can define a list of top level / other subject areas in the settings.py.

**Comment by MatMoore** [comment]
Slides for presenting the domain -> tag change to stakeholders

https://justiceuk.sharepoint.com/:p:/r/sites/DataCatalogue/Shared%20Documents/Show%20%26%20Tells/Find%20MoJ%20data%20more%20flexible%20subject%20area%20taxonomy%20-%20Dec%202024.pptx?d=w4c95ae42ce6c42008b6455d55526d305&csf=1&web=1&e=HnabWL
