### ISSUE TITLE
Typo for agency on agency_visit_slots dataset

### ISSUE THREAD

**Issue by teeceeas** [ministryofjustice/find-moj-data#1078]
https://find-moj-data.service.justice.gov.uk/details/table/urn:li:dataset:(urn:li:dataPlatform:dbt,cadet.awsdatacatalog.nomis_dbt.agency_visit_slots,PROD)

https://find-moj-data.service.justice.gov.uk/details/table/urn:li:dataset:(urn:li:dataPlatform:dbt,cadet.awsdatacatalog.nomis_sensitive.agency_visit_slots,PROD)

![Image](https://github.com/user-attachments/assets/ead50838-d320-449e-a707-265e9b3711da)

**Comment by murdo-moj** [comment]
I have edited the nomis glue database, which comes from nomis central. https://eu-west-1.console.aws.amazon.com/glue/home?region=eu-west-1#/v2/data-catalog/tables/view/agency_visit_slots?database=nomis_production_raw_hist&catalogId=593291632749

**Comment by murdo-moj** [comment]
It might get overwritten by the daily NOMIS extracts, so we'll see. If it does, the solution to this is to get NOMIS to update their table schema further upstream.
