### ISSUE TITLE
Make sure all components are documented

### ISSUE THREAD

**Issue by MatMoore** [ministryofjustice/find-moj-data#1097]
The purpose of this ticket is to make sure that we "Maintain up-to-date documentation for all implemented components, APIs, and dependencies to facilitate smooth collaboration and knowledge transfer within MOJ Digital"

We should make sure every component has a readme or other documentation, and remove anything that is out of date. Consider moving content into the runbooks where it makes sense.

- [x] [Find MOJ data repo](https://github.com/ministryofjustice/find-moj-data/blob/main/README.md)
- [x] [Custom frontend components](https://github.com/ministryofjustice/find-moj-data/blob/main/scss/components/README.md)
- [x] [The custom ingestion sources / transformers](https://github.com/ministryofjustice/data-catalogue/tree/main/ingestion)
- [ ] [Data catalogue repo](https://github.com/ministryofjustice/data-catalogue/blob/main/README.md)

**Comment by LavMatt** [comment]
mostly updated and reviewed.

Outstanding is the data catalogue repo [readme secrets section](https://github.com/ministryofjustice/data-catalogue/tree/main?tab=readme-ov-file#managing-database-secrets) - Currently has a circular flow for some postgres and opensearch secrets which may be unnecessary now. Will need further investigating and potentially streamlining and then the readme here should be updated accordingly
