### ISSUE TITLE
[Spike] Optimise metadata validation (CaDeT ingestion)

### ISSUE THREAD

**Issue by MatMoore** [ministryofjustice/find-moj-data#1098]
The purpose of this ticket is to "Explore enhancements in data entry and ingestion processes which could further optimise data integrity and reliability" - i.e. stuff we can do to prevent bad metadata from getting into Find MoJ data in the first place.

Decide whether we need additional validation of the metadata we're accepting from CaDeT.

- How might we want to constrain metadata beyond what Datahub accepts?
  - Currently we allow people to enter any email address for the data custodian - should we restrict this?
- What checks (if any) should run when people change data catalogue related metadata in the CaDeT repo?
- What checks (if any) should run before/during the datahub ingestion?

(A valid outcome of this spike is we decide it's fine as it is now)

**Comment by murdo-moj** [comment]
## Generally it makes sense to push data validations as far upstream as possible towards their source.

### What checks could we implement?

We can implement basic checks such as:
- Validate contact emails conform to an email regex
- Validate Enum fields are filled in with Enum values (we have a lot of these)
- Validate table names have characters in the set [a-z_]
- Validate timestamps are all in the past
- Validate created is before last updated

### How would we implement these checks?

- Custom checker script in CaDeT to push validations upstream
- Pydantic on our ingestions side (pretty far downsteam).

### What would we do if we detected poor metadata in our ingestions?

- In an ideal world, metadata validations are done and resolved at source. However we already have a lot of metadata and we generate a few of the fields we display (eg `Audience`) so we also need a feedback mechanism.
- We would want to alert the service we were ingesting from, so they could improve the data.
- We could feedback in the form of a report on metadata quality as a basic measure.
- Long term, each service could need to implement checks on their metadata at creation to enforce data quality.
- When finding issues using Pydantic we shouldn't change metadata we ingest to conform to our rules. We have the choice of:
    - Failing the ingestion and getting the provider to fix the issue
    - Or logging the issue, continuing the ingestion, and still getting the provider to fix the issue.

**Comment by murdo-moj** [comment]
Alternative idea: Metadata dashboard
