### ISSUE TITLE
"You are now leaving Find MoJ data" transitionary page

### ISSUE THREAD

**Issue by murdo-moj** [ministryofjustice/find-moj-data#1108]
### User story

As a user I want to be notified when I am leaving Find MoJ data to another gov.uk design pattern styled website.

### Context

Other govuk services we link to eg data.gov.uk have very similar styling. This makes it hard for the user to notice that they have left the service.

### Ideas

Make a transitionary page which informs users they are leaving FMD

**Comment by YvanMOJdigital** [comment]
check for moj design system component

**Comment by LavMatt** [comment]
This design as is with an auto redirect is bad for accessibility. I have reached out to the design slack channel in gov digital slack
https://ukgovernmentdigital.slack.com/archives/C062GAGLW/p1733825790263679

If we want to keep it we likely need to add a second click rather than automatically redirect

**Comment by joe-horton-moj** [comment]
Comments and recommendation left in [PR conversation](https://github.com/ministryofjustice/find-moj-data/pull/1153#pullrequestreview-2511367479).

**TL:DR** – don't implement a transitionary page for external links and monitor the issue in future UR sessions.

**Comment by LavMatt** [comment]
> Comments and recommendation left in [PR conversation](https://github.com/ministryofjustice/find-moj-data/pull/1153#pullrequestreview-2511367479).
> 
> **TL:DR** – don't implement a transitionary page for external links and monitor the issue in future UR sessions.
> 
> What are your thoughts [@LavMatt](https://github.com/LavMatt)? I think you came to same reasoning last time we discussed in on stand-up?

Yeah totally agree with your comments Joe. If it continues to be a problem arise in future UR, we should explore solutions other than creating a transitionary page around design and stronger brand identity within our service.

I shall close the PR
