### ISSUE TITLE
Remove advanced search link from drop down 

### ISSUE THREAD

**Issue by jemnery** [ministryofjustice/find-moj-data#1115]
When we reveal search tips with the details component, we're including a link for [More advanced search options](https://datahubproject.io/docs/how/search/#advanced-queries)

- This opens in the same tab, taking users away from the service to a different site
- Are these options *too* advanced for most users? Will terms like "pattern matching", "logical expressions", "tokenization" be offputting? Does it give the feeling of stumbling into an area you're not supposed to be in? (Like the GitHub link in the user guide)

---

![Image](https://github.com/user-attachments/assets/5480057d-502b-4b44-89c1-dbe00ced7fbd)

**Comment by YvanMOJdigital** [comment]
remove more advanced search. review search tips with Sabrina.
