### ISSUE TITLE
find-moj-data: search term highlight tags

### ISSUE THREAD

**Issue by jemnery** [ministryofjustice/find-moj-data#114]
Check this is true, but I _think_ when we highlight search terms the correct accessible approach is to use `<mark>` tags

E.g. instead of

```html
<p>Derived table that has one row per <strong>offence</strong> for all defendants across all cases</p>
```

Do this

```html
<p>Derived table that has one row per <mark>offence</mark> for all defendants across all cases</p>
```

And then style the `font-weight` of `mark`. 

Live example from our publications search [here](https://www.gov.uk/search/research-and-statistics?keywords=offence&content_store_document_type=statistics_published&organisations%5B%5D=ministry-of-justice&order=relevance).

**Comment by mitchdawson1982** [comment]
- Strong tags in the example below are being rendered by the markdown template function.
