### ISSUE TITLE
Accessibility

### ISSUE THREAD

**Issue by seanprivett** [ministryofjustice/find-moj-data#131]
Plan for beta
Output of consultation
Design choices
Why DataHub isn't suitable
Iterations to design
Evidence of testing with people with accessibility needs (15%)

**Comment by jemnery** [comment]
The service assessment desk can used as a basis for this: https://docs.google.com/presentation/d/1gceWOAYirgbLcaw3zKRbg1r98BLuIZW-xgFbxZdslmA/edit#slide=id.g2b75f47d2f8_0_0
