### ISSUE TITLE
Service runbook

### ISSUE THREAD

**Issue by seanprivett** [ministryofjustice/find-moj-data#152]
Create service runbook
Use Mod Platform template
Use Github pages

**Comment by tom-webber** [comment]
Runbook documentation organisation and deployment options:

1. Cloud Platform's (CP's) runbooks
    1.  [organisation](https://github.com/ministryofjustice/cloud-platform/tree/main/runbooks):
        1. [`runbooks` directory](https://github.com/ministryofjustice/cloud-platform/tree/main/runbooks) in the top level `cloud-platform` repo contains the source files for the runbooks
    2. deployment:
        1. A github action compiles the source files from this directory to html, and updates a [dedicated target repository](https://github.com/ministryofjustice/cloud-platform-runbooks).
2. Data Platform's (DP's) user guide
    1. organisation
        1. [`docs` directory](https://github.com/ministryofjustice/cloud-platform/tree/main/runbooks) in the top level `data-platform` repo contains the source files for the user-guide
    2. [deployment](https://github.com/ministryofjustice/data-platform/blob/main/.github/workflows/documentation.yml)
        1. approved changes are automatically compiled to an artefact and deployed to github pages.
4. Analytical Platform's (AP's) user guide     
    1. organisation:
         1. dedicated [user-guide repo](https://github.com/ministryofjustice/analytical-platform-user-guide)
    2. [deployment](https://github.com/ministryofjustice/analytical-platform-user-guide/blob/main/.github/workflows/publish.yml)
         1. approved changes are automatically compiled to an artefact and deployed to github pages.

Going to follow AP's method, as this separates the intent and purpose into a distinct repository. The top level data-catalogue repo will contain a link to this repo.

**Comment by tom-webber** [comment]
[Runbooks](https://github.com/ministryofjustice/data-catalogue-runbooks)
[User Guide](https://github.com/ministryofjustice/data-catalogue-user-guide) was also created as its the same steps.

Steps for creation:
- [add repository to repo-management terraform with pages configured](https://github.com/ministryofjustice/data-platform/pull/3866/files#diff-3b2339d89b7042b42a85cee964109fd7d64aebb61a3a40c710a955aea5807602R118-R125)
- [send an email to domains@digital.justice.gov.uk requesting the DNS zone](https://mojdt.slack.com/archives/C01BUKJSZD4/p1711378720448109?thread_ts=1711375871.456529&cid=C01BUKJSZD4)
