### ISSUE TITLE
Define fields to be used for frontend searches and displaying of results

### ISSUE THREAD

**Issue by mitchdawson1982** [ministryofjustice/find-moj-data#17]
# User story
As a developer I need to define which data product fields will be made available to users so that they are able to search and filter efficiently and recognise requested data products in search results.

# Value / Purpose
Displaying accurate and relevant data to users will provide better catalogue experiences for users

# Background
Users will be using the frontend application search or browse data products. The search and filter capabilities will need to utilise fields that reside within data product metadata in Datahub in order to locate respective data products. Similarly when results are returned from datahub to be rendered in the front end we  need to decide which fields to display to users.

Considerations
- It would be beneficial to pass frontend selected search and or filter values to datahub without alteration or mapping between the two to avoid complication.
- Filtering and Search fields should be present on the search result objects to aid user feedback.
- A more detailed response with additional fields should be rendered when the user has requested a specific data product.

# Definition of done

- [ ] We have identified which Datahub metadata fields to use to filter and search data products results.
- [ ] We have identified which Datahub metadata fields to use to render a single data products result.

**Comment by mitchdawson1982** [comment]
Waiting for the outcome of Murdo's ticket

**Comment by MatMoore** [comment]
Latest specification for the metadata fields
https://docs.google.com/spreadsheets/d/1O1EjO96lyqDbyuzFWU8SNBky3b7tKM8dccZVS7-_t9g/edit#gid=784169301

As soon as https://github.com/ministryofjustice/data-platform/pull/3134 is merged we will be able to access customProperties in the frontend
