### ISSUE TITLE
Search results - should asset type "dataset", "chart" (etc) identifiers be captions not tags?

### ISSUE THREAD

**Issue by jemnery** [ministryofjustice/find-moj-data#197]
In search results we identify the asset type with a `govuk-tag` element in the `<h3>`. Should these be `govuk-caption-*` elements instead? Does this make more sense for page order and screen readers? It would be more consistent with the detail pages.

Before & after:

**Before**

<img src="https://github.com/ministryofjustice/find-moj-data/assets/1306705/65b5b87c-a5ea-4e77-887e-d168bb737bc5" width="500" />

<hr />

**After**

<img src="https://github.com/ministryofjustice/find-moj-data/assets/1306705/22f8d061-9c8d-49f5-a810-840ed1a2f13e" width="500" />

**Comment by MatMoore** [comment]
This looks like a good idea to me. 👍🏻 

The details page already uses captions - so this would create consistency between the two

<img width="679" alt="Screenshot 2024-04-09 at 16 27 19" src="https://github.com/ministryofjustice/find-moj-data/assets/87579/420af6e3-cf2c-4979-8cf3-47df0522ea55">
