### ISSUE TITLE
🐛 CSS can be cached causing pages to not be rendered as expected

### ISSUE THREAD

**Issue by LavMatt** [ministryofjustice/find-moj-data#206]
### Describe the bug.

cached data can cause pages in `find-moj-data` to not be rendered with the intended styling

This is because we're not changing the application.css filename when our CSS changes, so the browser is free to use a cached version, even when we've released new templates.

Normally this is solved with "cache busting" URLs/filenames - see https://blog.risingstack.com/automatic-cache-busting-for-your-css/

Since we already run our CSS through a sass compiler, we should be able to add in a hash to the resulting file, but we need to make sure this plays nicely with Django's staticfiles helpers.

And we will have the same problem for the javascript and images as well.

**Comment by murdo-moj** [comment]
https://docs.djangoproject.com/en/5.0/ref/contrib/staticfiles/#manifeststaticfilesstorage We can use this class in Django as `STATICFILES_STORAGE`, which should force the cache to update when eg the css changes.

It appends the file hash to a file name in the backend, so:
- `static/oldfile.css` resolves in the backend to `static/oldfile.523j4hjhfs.css`, and the file is cached with a hash
- Then, the css is updated.
- `static/oldfile.css` now resolves in the backend to `static/oldfile.666gsdegs.css`, so the cached old file is invalidated and the new file is pulled

**Comment by murdo-moj** [comment]
https://github.com/ministryofjustice/find-moj-data/pull/331
