### ISSUE TITLE
Add Google Analytics to find-moj-data

### ISSUE THREAD

**Issue by jemnery** [ministryofjustice/find-moj-data#232]
Capture standard GA events - visits, click etc. **No PII data to be collected.**

May want / need to capture custom events to examine glossary usage.

Assume (pre)prod only.

Create with our own .digital emails and add all team to group

Can we track search terms?

**Comment by jemnery** [comment]
[SNOW request](https://mojprod.service-now.com/moj_sp?id=ticket&table=sc_req_item&sys_id=85c898121b558210de03620be54bcb19&view=sp) submitted

**Comment by MatMoore** [comment]
Created an account data-catalogue with property data-catalogue-production

Initial settings, which will need to be reviewed from a security POV before pushing to prod

![Image](https://github.com/ministryofjustice/find-moj-data/assets/87579/6a7a24f4-f08c-4b80-8aea-6f3c7160a375)
![Image](https://github.com/ministryofjustice/find-moj-data/assets/87579/19f6147d-7bcb-47f5-ace7-2e8015cb5895)

**Comment by MatMoore** [comment]
Added a search terms report following these instructions: https://www.analyticsmania.com/post/track-site-search-with-google-tag-manager-and-google-analytics/

Haven't tested it yet as it takes time for data to come through

**Comment by MatMoore** [comment]
Relevant docs from LAA on using GA https://dsdmoj.atlassian.net/wiki/spaces/LTA/pages/4603609873/Web+analytics+guardrail

**Comment by MatMoore** [comment]
Guidance on avoiding PII leakage https://support.google.com/analytics/answer/6366371?hl=en#zippy=%2Cin-this-article

In our case

- we don't currently have any PII in page titles or URLs
- the search query could be a vector for sending PII, but this is low risk
- [there is a mitigation for redacting email address in query strings](https://www.monsterinsights.com/how-to-easily-keep-pii-out-of-google-analytics/)
- if we add anything to track when the user makes a contact request, we should be careful not to submit names and email addresses to GA. But this is not implemented yet
- when we build forms for submitting metadata, we will be using POST forms and not submitting any PII
