### ISSUE TITLE
Spike: Search doesn't perform very well with multiple words

### ISSUE THREAD

**Issue by seanprivett** [ministryofjustice/find-moj-data#248]
- Currently, search on datahub with multiple words matches the whole search string exactly to results
- This means that any typo or error in word order results in few or zero search results
- This restricts the practical use of the search functionality to 2 or 3 words
---
- DataHub offers some flexibility in how it's search works
- Currently the exclusive match setting is set to false, yet we can see that the search is exclusive. We've asked datahub about this on Slack, but have no response yet
---
- What do we want search behaviour to be like? We don't really know.

**Comment by YvanMOJdigital** [comment]
spike to investigate options for improving search results when using multiple words

**Comment by MatMoore** [comment]
I started investigating this last week and wrote some notes here: https://mojdt.slack.com/archives/C03QZ776JVA/p1712233855118319

**Comment by murdo-moj** [comment]
Pasting Mat's notes from slack:

```Dug into this a bit more. This is our current config, with no customisations:
    ## Search related configuration
    search:
      ## Maximum terms in aggregations
      maxTermBucketSize: 20

      ## Configuration around exact matching for search
      exactMatch:
        ## if false will only apply weights, if true will exclude non-exact
        exclusive: false
        ## include prefix exact matches
        withPrefix: true
        ## boost multiplier when exact with case
        exactFactor: 2.0
        ## boost multiplier when exact prefix
        prefixFactor: 1.6
        ## stacked boost multiplier when case mismatch
        caseSensitivityFactor: 0.7
        ## enable exact match on structured search
        enableStructured: true
What's interesting to me is it has exclusive: false, so non-exact matches are not supposed to be excluded
Here is a test case demonstrating that non-exact matches are excluded:
query {
  searchAcrossEntities(
    input: {
      query: "An abscond is an escape that does not involve overcoming a physical security restraint"
    }
  ) {
    total
  }
}
-> match
query {
  searchAcrossEntities(
    input: {
      query: "An abscond is an escape that does not involve overcoming a gorilla"
    }
  ) {
    total
  }
}
-> does not match
[The same behaviour is visible in the datahub UI, so it doesn't look like something we've introduced.](https://datahub-catalogue-preprod.apps.live.cloud-platform.service.justice.gov.uk/search?page=1&query=An%2520abscond%2520is%2520an%2520escape%2520that%2520does%2520not%2520involve%2520overcoming%2520a%2520gorilla&unionType=0)
From my examination of the datahub search code, I would expect this to still match. On [this line](https://github.com/datahub-project/datahub/blob/dc16c73937dcb4a287653090faf3c32807257872/metadata-io/src/main/java/com/linkedin/metadata/search/elasticsearch/query/request/SearchRequestHandler.java#L233), the whole elasticsearch query is wrapped in a [must clause](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-bool-query.html), which means the internal query needs to match for something to be included in the results. But the internal query itself uses "should" clauses. The built in subqueries are called simpleQuery, prefixMatchQuery, and exactMatchQuery. Of these, the simpleQuery should match even if there is a missing term, and [it always gets used if exclusive=false](https://github.com/datahub-project/datahub/blob/dc16c73937dcb4a287653090faf3c32807257872/metadata-io/src/main/java/com/linkedin/metadata/search/elasticsearch/query/request/SearchQueryBuilder.java#L303).
So it seems to me that there is a bug somewhere in datahub, or somewhere along the line it is deliberately adding quotes around the query string. Possibly we could crank up the logging in elasticsearch to see what is actually getting through, but I'm going to query this on datahub slack and see if I'm missing anything.
```

**Comment by murdo-moj** [comment]
https://runbooks.data-catalogue.service.justice.gov.uk/documentation/runbooks/003-search.html#how-the-graphql-api-translates-queries-into-elasticsearch-queries

**Comment by seanprivett** [comment]
We need more data from GA plugged into the search page in order to be able to customise this.

The default search is very configurable if you know the search shortcuts - detailed [here](https://datahubproject.io/docs/how/search/).

Is there a way to surface this to our early adopters, who will probably be very comfortable using this syntax, while we build a better picture of search pathways?

**Comment by MatMoore** [comment]
Quotes, &, | syntax all work as expected via our interface. It's just that if you don't specify an operator, it assumes & (AND) rather than  | (OR), which is what we would expect (i.e. matching the behaviour of [elasticsearch's simple query](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-simple-query-string-query.html))

For now I will include a details component that explains this syntax.

If datahub view this default behaviour as a bug, this might change in a future version, otherwise, we should gather data from GA, then consider customising the elastcisearch configuration.
