### ISSUE TITLE
Set up Cloud Platform Alerting for Find-MoJ-Data

### ISSUE THREAD

**Issue by tom-webber** [ministryofjustice/find-moj-data#272]
### User Story

Follows on from ministryofjustice/find-moj-data#230, similar to ministryofjustice/data-catalogue#29

Set up monitoring-based alerting for:

- Find MOJ data front end

[Cloud Platform guide to observability](https://user-guide.cloud-platform.service.justice.gov.uk/#observability)

#### PagerDuty

Consider (if time) adding PagerDuty as a middleware broker for what/where/when. Even if we're not actually implementing an on-call rota.

### Requirements
- [ ] [Define and deploy custom alerts with PrometheusRule](https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts)
  - [x] high latency
  - [ ] errors
  - [x] resource depletion
  - [ ] security anomalies
- [x] Set up [pingdom](https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-pingdom-checks.html#creating-pingdom-checks) to alert if either of our main services (or important endpoints) go down

### Hypothesis

If we... [do a thing]
Then... [this will happen]

### Definition of Done

Example - [ ] Documentation has been written / updated
- [ ] README has been updated
- [ ] User docs have been updated
- [ ] Another team member has reviewed
- [ ] Tests are green

**Comment by LavMatt** [comment]
errors are handled by sentry alerting, security anomalies will be better looked at when we have azure auth. Currently get a lot of bogus 403s
