### ISSUE TITLE
🐛 gracefully handle errors when items missing in underlying metadata store

### ISSUE THREAD

**Issue by tom-webber** [ministryofjustice/find-moj-data#276]
### Describe the bug.

It's possible to query for objects that don't exist on the DataHub instance (due to differences between environments), which currently returns an error. This should be handled rather than returning an error as it causes confusion during development. It's unlikely that such searches would be possible to encounter in the production environment.

### To Reproduce

`KeyError` for `properties["name"]` when filtering for Databases (containers) on the `dev` DataHub instance (prior to databases being added / implemented).

### Expected Behaviour

A search with 0 entries because none are present on the instance should return 0 results, rather than a key error.

**Comment by murdo-moj** [comment]
There's now a switch in the search method of the datahub client to return an empty SearchResponse when the total results returned from DataHub is 0

**Comment by murdo-moj** [comment]
As part of the refactor we added 404 responses when a table/database/chart urn isn't found

**Comment by MatMoore** [comment]
- The 404 response is working as expected on the details page
- I've added a partial to render a (hopefully) helpful message in the event that search returns no results https://github.com/ministryofjustice/find-moj-data/pull/320

The copy may need to be improved later, but this allows us to handle this case without blowing up and without rendering unnecessary parts of the page like pagination
