### ISSUE TITLE
Spike: Create version 1 of our metadata spec

### ISSUE THREAD

**Issue by seanprivett** [ministryofjustice/find-moj-data#278]
We have an existing spec on a spreadsheet.
Consult with DIP team to see what their latest requirements are
Evaluate the spec that ONS has devised.

Here is the [general metadata guidance](https://www.gov.uk/government/publications/recommended-open-standards-for-government/using-metadata-to-describe-data-assets-in-a-data-catalogue) from Data Marketplace

Also look at the metadata spec for Essential Shared Data Assets

Output: version 1 of the FMD metadata spec, ready for front end design for registration, and for configuring DataHub.

Pydantic metadata schema that we currently have.

Which format do our customers want this spec?

Details of our version 1 in [this ticket](https://github.com/ministryofjustice/data-platform/issues/2781)

**Comment by murdo-moj** [comment]
https://erdantic.drivendata.org/stable/

**Comment by seanprivett** [comment]
Please pair with @alex-vonfeldmann on this

**Comment by murdo-moj** [comment]
https://docs.google.com/spreadsheets/d/1O1EjO96lyqDbyuzFWU8SNBky3b7tKM8dccZVS7-_t9g/edit#gid=756355926 here's the old spec

 https://github.com/ministryofjustice/find-moj-data/blob/main/lib/datahub-client/data_platform_catalogue/entities.py here's the PyDantic entities we have in code

**Comment by seanprivett** [comment]
New version available [here](https://docs.google.com/spreadsheets/d/1O1EjO96lyqDbyuzFWU8SNBky3b7tKM8dccZVS7-_t9g/edit#gid=1846443805) in advance of our team session on Thursday. Orange highlights are where there are questions about amendment or removal, red highlights are suggested removals.
