### ISSUE TITLE
Automate Justice Data / CaDeT Domain Ingestions

### ISSUE THREAD

**Issue by MatMoore** [ministryofjustice/find-moj-data#291]
### User Story

As a catalogue user
I expect metadata to be regularly refreshed
So that I can find data

### Value / Purpose

https://github.com/ministryofjustice/datahub-custom-api-source was created during alpha to ingest from the Justice Data API

Scheduling this to run automatically ensures we keep this up to date.

https://github.com/ministryofjustice/datahub-custom-domain-source ingests domains from Create a derived table.

Scheduling this to run automatically means we don't have to manage the domain model ourselves.

### Proposal

Based on https://github.com/ministryofjustice/data-catalogue/issues/19
We think the easiest way to deploy this will be to set up a github actions workflow in the data-catalogue-metadata repo.

This already has a token set up to connect to datahub instances.

- [ ] Set up a scheduled workflow for each environment (e.g. weekly - Justice Data prod upgrades usually 2x per month)
- [ ] Commit an ingestion recipe that ingests from the justice api source (see readme)
- [ ] Commit an ingestion recipe that ingests from the domains source (see readme)
- [ ] The workflow should run the `datahub ingest` command for each recipe and environment

**Comment by seanprivett** [comment]
Can be disruptive if this is enabled on a schedule in dev environment.
Decided not to switch on scheduling at this stage
