### ISSUE TITLE
🐛 Database breadcrumb not rendering properly

### ISSUE THREAD

**Issue by MatMoore** [ministryofjustice/find-moj-data#321]
### Describe the bug.

Here we have a database called _investigations_dev
https://datahub-catalogue-dev.apps.live.cloud-platform.service.justice.gov.uk/container/urn:li:container:5d498bf254eb0d57dca68f879b762052/Entities?is_lineage_mode=false

Renders OK here: http://localhost:8000/details/database/urn:li:container:5d498bf254eb0d57dca68f879b762052

But the breadcrumb here is missing a name and it renders funny

![Breadcrumb is missing the middle section](https://github.com/ministryofjustice/find-moj-data/assets/87579/e0397207-dacd-435d-b3f7-857510143334)

**Comment by murdo-moj** [comment]
https://data-platform-find-moj-data-dev.apps.live.cloud-platform.service.justice.gov.uk/details/database/urn:li:container:5d498bf254eb0d57dca68f879b762052

I can't reproduce this 😕

**Comment by murdo-moj** [comment]
https://github.com/ministryofjustice/find-moj-data/pull/338
