### ISSUE TITLE
Spike: Underscore behaviour in search

### ISSUE THREAD

**Issue by seanprivett** [ministryofjustice/find-moj-data#324]
What are the options we have to mitigate this issue? 

Issue raised with DataHub: https://datahubspace.slack.com/archives/C029A3M079U/p1714733851141439

Here's the original Slack thread in our channel which explains the issue with examples: https://mojdt.slack.com/archives/C03QZ776JVA/p1714728291635949

One solution:
- Straight replace underscores with spaces. This gets similar results, is quick to implement, and quick to rollback.

**Comment by murdo-moj** [comment]
Raised a bug as well as poked them on Slack https://github.com/datahub-project/datahub/issues/10505

**Comment by murdo-moj** [comment]
https://datahubspace.slack.com/archives/C029A3M079U/p1715761935519539

**Comment by murdo-moj** [comment]
https://github.com/ministryofjustice/find-moj-data/pull/355
