### ISSUE TITLE
Spike: create database level metadata during CaDeT ingestion

### ISSUE THREAD

**Issue by seanprivett** [ministryofjustice/find-moj-data#393]
## Context
[Link to Miro board](https://miro.com/app/board/uXjVNPsG_-I=/?moveToWidget=3458764591203719413&cot=14)

Tables/models ingested from CaDeT are in a hierarchy, with the top level known as the database level.
Database information is very relevant for our users, but there isn't currently a way to get this into the catalogue

Is the assumption for this ticket that we are just creating the database level name?

**Questions from Miro session:**

* Can we traverse from DBT model -> athena table -> athena database?
* Custom transformer to create/associate a container with an entity
* Are the top level databases tagged as sources?
* Can we do this with tags?
* Identify existing database by name?
* Advantage of automated tie-in to live data. If a new source database starts getting used, we get it automatically. If a source database goes away, it'll be removed

## Requirements:
- [ ] pick a single method for implementing the creation of the database level during dbt ingestion 
- [ ] describe / outline the chosen method for implementation

**Comment by murdo-moj** [comment]
https://github.com/ministryofjustice/data-catalogue/pull/151
