### ISSUE TITLE
Spike: Explore analytics options for tracking user journeys in DataHub

### ISSUE THREAD

**Issue by seanprivett** [ministryofjustice/find-moj-data#396]
Do any datahub logs provide us with useful user analytics.

What do Acryl have to say about analytics? 

We would like to track user behaviour in datahub what are our options? 

https://datahubproject.io/docs/datahub-web-react/src/app/analytics/

**Comment by murdo-moj** [comment]
[We have looked at logging in datahub before](https://github.com/ministryofjustice/find-moj-data/issues/229)

**Comment by murdo-moj** [comment]
[The entity events api has event logs like we'd want, but it's only available in managed DataHub.](https://datahubproject.io/docs/managed-datahub/datahub-api/entity-events-api/)

**Comment by MatMoore** [comment]
Some possible options...

## Develop the GA support & no-code configuration support ourselves

- no maintenance burden for us long term 👍 
- the existing GA plugin is very small and shouldn't be much work to update to GA 4 👍  https://github.com/datahub-project/datahub/blob/master/datahub-web-react/src/app/analytics/plugin/googleAnalytics.ts 
- there are docs here https://github.com/datahub-project/datahub/tree/master/datahub-web-react/src/app/analytics 
- no-code configuration support will require some back and forth on the design  👎 
- but could do this in stages 

## Proxy datahub requests through something that alters the HTML
- modify outgoing responses to inject a GA tag
- this would allow us to track page views but no other events (it would bypass Datahub's framework)  👎 
- complicates the support model, as our deployment would diverge from the Datahub provided helm charts  👎 
- we have to maintain extra code  👎 

## Use GA Data import
- It's possible to import extra data as "offline events" https://support.google.com/analytics/answer/10325025
- We would need some custom code to export events from datahub  👎 
- This would not work in realtime  👎 
- Find MOJ Data would need to pass a user id so we can link the journeys across the two sites https://support.google.com/analytics/answer/9213390?hl=en

**Comment by MatMoore** [comment]
When configuring the existing GA plugin locally, it seems to work without any errors

It runs the following commands internally (via GA debug browser plugin)

```
Running command: ga("set", "userId", "urn:li:corpuser:datahub")

Running command: ga("send", "pageview", {page: "/", title: "DataHub", location: "http://localhost:3000/"})

Running command: ga("send", "event", {hitType: "event", eventAction: "RecommendationImpressionEvent", eventLabel: "urn:li:corpuser:datahub", eventCategory: "UserActions", nonInteraction: false})
```

So far, this is as expected.

Since we have two sites we want to analyse together, we should share the existing account and property, but add another stream in GA.

Still to do

- [ ] Validate that page views are received by GA
- [ ] [Check to see if any events need mapping](https://support.google.com/analytics/answer/11091025#zippy=%2Cin-this-article)

GA UA->4 migration docs are here https://support.google.com/analytics/answer/10759417?hl=en&ref_topic=12154439,12153943,2986333

**Comment by MatMoore** [comment]
Datahub depends on Google Analytics via [this analytics library](https://github.com/DavidWells/analytics#readme)

        "@analytics/google-analytics": "^0.5.2",

Latest version is 1.0.7, and [1.0.0](https://github.com/DavidWells/analytics/blob/master/packages/analytics-plugin-google-analytics/CHANGELOG.md#100-2022-06-15) is when they switched from GA3 to GA4

Universal Analytics stopped collecting data a year ago and is being turned off in a month, so no need to support it still.
