### ISSUE TITLE
Code changes from new metadata spec: back end

### ISSUE THREAD

**Issue by seanprivett** [ministryofjustice/find-moj-data#404]
See https://docs.google.com/spreadsheets/d/1O1EjO96lyqDbyuzFWU8SNBky3b7tKM8dccZVS7-_t9g/edit#gid=1846443805

and the previous spike https://github.com/ministryofjustice/find-moj-data/issues/363

## Purpose

We are adding new custom properties to Datahub that will come from DBT metadata. These will be used render the contact/where to access panel on the details page.

| field name | description | example |
| -- | -- | -- |
| dc_slack_channel_name | The name of a slack channel to be used as a contact point for users of the catalogue service, including the leading '#'. Note: this is not the same as the owner channel for notifications. | `#data-engineering` |
| dc_slack_channel_url | The URL to the slack channel | `https://moj.enterprise.slack.com/archives/C8X3PP1TN` |
| dc_where_to_access_dataset | An enum representing how the data can be accessed by end users. For DBT, this always defaults to AnalyticalPlatform. | AnalyticalPlatform |

## Required changes
- [x] Extend our metadata model to include these custom properties
- [x] Ensure these 3 attributes are passed back to the frontend
- [x] Ensure the metadata documentation page renders correctly
- [x] Ensure any references to `where_to_access_dataset` use the new prefixed property name

**Comment by tom-webber** [comment]
>Ensure the metadata documentation page renders correctly

[The `Field` in the metadata should reflect the name of the field when snake case, but currently capitalises with spaces](https://github.com/ministryofjustice/find-moj-data/issues/411)
