### ISSUE TITLE
Placeholder: UI tweaks

### ISSUE THREAD

**Issue by jemnery** [ministryofjustice/find-moj-data#423]
A placeholder issue to note down front-end tweaks - [Slack post](https://mojdt.slack.com/archives/C03QZ776JVA/p1718121164349819)

We can refine / split into separate tickets once we know how much change is needed.

- [ ] Drop **registered by**
- [ ] Hide metadata fields when they are empty - currently inconsistent - done for table details but not other entities
- [ ] Make sure page title is set on 404 and error pages

**Comment by MatMoore** [comment]
Noticed another issue while testing - 404 page template assumes a variable is set, but it isn't

```
DEBUG 2024-06-12 11:15:15,383 base 2224 140130622895680 Exception while resolving variable 'h1_value' in template '404.html'.
```

**Comment by alex-vonfeldmann** [comment]
if subdomains are out: should we remove subdomain selection and go with single domain selection only?

**Comment by alex-vonfeldmann** [comment]
name and surname of data owners derived from email are not capitalized:
https://data-platform-find-moj-data-test.apps.live.cloud-platform.service.justice.gov.uk/details/database/urn:li:container:ARIA

**Comment by alex-vonfeldmann** [comment]
metadata labels should be consistent throughout all screens - 

"Last updated date" as seen here is redundant, should be last updated 
https://data-platform-find-moj-data-test.apps.live.cloud-platform.service.justice.gov.uk/details/database/urn:li:container:ARIAeir

**Comment by alex-vonfeldmann** [comment]
richard t's UR brought up that 'ascending' and 'descending' labels for the search sort are meaningless because it might mean A-Z, updated, added ... 

what does this sort by? 'most recently updated' or 'most recently added to the catalogue'?

**Comment by alex-vonfeldmann** [comment]
all environments should use the same service header (currently dev uses the new one but test the old one)

**Comment by alex-vonfeldmann** [comment]
text on detail page should have the same left alignment (bottom para sits more to the left) 

![Image](https://github.com/ministryofjustice/find-moj-data/assets/115145706/e8b7f176-944f-49ad-8172-dffee0d3fe0f)

**Comment by alex-vonfeldmann** [comment]
should default state of filter component show 'selected filters' when no filters are applied? 

![Image](https://github.com/ministryofjustice/find-moj-data/assets/115145706/11e20546-ff77-4743-a142-9a6be48c305a)

**Comment by alex-vonfeldmann** [comment]
could the search have an 'x' to clear action button when active and not empty? just like on gov.uk search?



![Image](https://github.com/ministryofjustice/find-moj-data/assets/115145706/91a43466-bfb0-4de5-843d-f6c2c6e81477)

**Comment by alex-vonfeldmann** [comment]
the title of a detail page should not be 'detail' but the actual thing 

test/dev 
![Image](https://github.com/ministryofjustice/find-moj-data/assets/115145706/75ac19b1-1a65-4d6e-ae99-6652e492ee3e)

vs figma
![Image](https://github.com/ministryofjustice/find-moj-data/assets/115145706/bed52d19-efbe-4361-a3a6-23d16baf2b2f)

**Comment by seanprivett** [comment]
@seanprivett follow up session on Tuesday 18th to split all front end work here into separate tickets

**Comment by alex-vonfeldmann** [comment]
take out 'this service is in beta' banner

**Comment by alex-vonfeldmann** [comment]
revisit link to 'metadata specification' on homepage:
- should this be in the page body? 

metadata specification page:
- lefthand navigation needs mreo spacing
