### ISSUE TITLE
update client's `get_database_details()` method to return only display tagged tables

### ISSUE THREAD

**Issue by LavMatt** [ministryofjustice/find-moj-data#435]
Filter for tagged tables

**Comment by MatMoore** [comment]
It looks like the `entities` field is handled by this resolver: https://github.com/datahub-project/datahub/blob/master/datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/container/ContainerEntitiesResolver.java

But this does not use the filter param, even though it is a valid field.

```java
    final String query = input.getQuery() != null ? input.getQuery() : "*";
    final int start = input.getStart() != null ? input.getStart() : 0;
    final int count = input.getCount() != null ? input.getCount() : 20;
```

I'll report this as a bug but for now we can workaround it by filtering in python.
