### ISSUE TITLE
Home page: browse by domain and search bar

### ISSUE THREAD

**Issue by seanprivett** [ministryofjustice/find-moj-data#437]
https://www.figma.com/design/zTOVhHRnWfxRJqH6Gr8cIc/Catalogue-sketches?node-id=703-3098&t=eAr8jTCsH7BuqGk8-0

**Comment by seanprivett** [comment]
Alex and Mat working on design to present search bar on same page as domain browsing feature

**Comment by alex-vonfeldmann** [comment]
very barebones design with search on home page (search stolen from gov.uk homepage)

![Image](https://github.com/ministryofjustice/find-moj-data/assets/115145706/f41a73fe-9c91-4cea-927c-fe3224897964)

**Comment by MatMoore** [comment]
This one also touches the search component - maybe look at both together https://github.com/ministryofjustice/find-moj-data/issues/459

**Comment by MatMoore** [comment]
The blue bit is the "masthead"

CSS here https://github.com/alphagov/govuk-design-system/blob/b3223714d8f2e9564b7e9d2ca703a3f902bf1ce8/src/stylesheets/components/_masthead.scss#L2
