### ISSUE TITLE
Left align bug on details page

### ISSUE THREAD

**Issue by jemnery** [ministryofjustice/find-moj-data#456]
> text on detail page should have the same left alignment (bottom para sits more to the left) 
> 
> ![Image](https://github.com/ministryofjustice/find-moj-data/assets/115145706/e8b7f176-944f-49ad-8172-dffee0d3fe0f)
> 
>  

Example:https://data-platform-find-moj-data-test.apps.live.cloud-platform.service.justice.gov.uk/details/database/urn:li:container:AlcoholMonitoringSystem

Possibly caused by nested `govuk-grid-row` ?

![Image](https://github.com/ministryofjustice/find-moj-data/assets/1306705/1adbacc6-f712-404c-a668-226993564f0c)

**Comment by tom-webber** [comment]
Note: each detail page has its own template, and so templates for chart, database, and tables give different indenting styles. It may be worth [creating a detail template parent and inheriting from that](https://docs.djangoproject.com/en/5.0/ref/templates/language/#template-inheritance).

**Comment by hjribeiro-moj** [comment]
Issue is less noticeable now with the work done with page templates, and although still visible, it has been de-prioritized
