### ISSUE TITLE
Display table name only

### ISSUE THREAD

**Issue by seanprivett** [ministryofjustice/find-moj-data#471]
In the search page, can we display table name instead of fully qualified name?
e.g.
current: [cadet.awsdatacatalog.bold_common_platform_linked_tables.all_offence](https://data-platform-find-moj-data-preprod.apps.live.cloud-platform.service.justice.gov.uk/details/table/urn:li:dataset:(urn:li:dataPlatform:dbt,cadet.awsdatacatalog.bold_common_platform_linked_tables.all_offence,PROD))
proposed: [all_offence](https://data-platform-find-moj-data-preprod.apps.live.cloud-platform.service.justice.gov.uk/details/table/urn:li:dataset:(urn:li:dataPlatform:dbt,cadet.awsdatacatalog.bold_common_platform_linked_tables.all_offence,PROD))

**Comment by seanprivett** [comment]
Sean to create ticket on research/design board: design work required to show database parent for a table in the search results page. If we are taking the parent out of the table name display

**Comment by jemnery** [comment]
Display as: **all_offence (bold_common_platform_linked_tables_all)** ??

Assumes "`cadet`" and "`awsdatacatalog`" aren't that helpful?

**Comment by alex-vonfeldmann** [comment]
design for review: 

![Image](https://github.com/ministryofjustice/find-moj-data/assets/115145706/7193a3d0-10e0-4341-b47a-3fba5ffcf5c6)
