### ISSUE TITLE
Create "go to production" tickets

### ISSUE THREAD

**Issue by jemnery** [ministryofjustice/find-moj-data#489]
Based on environments meeting and [this MIro board](https://miro.com/app/board/uXjVK8MOx_c=/)

### GitHub actions improvements (one ticket)

https://github.com/ministryofjustice/find-moj-data/issues/498

### Create prod env

https://github.com/ministryofjustice/find-moj-data/issues/494

**Comment by MatMoore** [comment]
Example of jobs left in a waiting state: https://github.com/ministryofjustice/find-moj-data/actions/workflows/test-and-deploy.yml

Github treats the deploy to dev as a thing that *has* to happen, but actually it is optional, and we don't need to do it for every single commit.

- Can these actions be invalidated by later jobs on the same branch?
- Should we take this out of the workflow entirely and just have a workflow_action trigger for dev?
