### ISSUE TITLE
✨ Deploy production instance of datahub

### ISSUE THREAD

**Issue by MatMoore** [ministryofjustice/find-moj-data#493]
Part of https://github.com/ministryofjustice/find-moj-data/issues/494

### Value / Purpose

We need datahub in prod before we can deploy Find MOJ data to Prod

### Proposal

- Define the new environment in Github actions / 1pass (The github environment should be approval gated)
- Create the namespace in Cloud Platform, including the opensearch & postgres instances
- Add required secrets and environment variables, including Entra ID configuration
- Modify the deploy workflow to trigger the prod deploy in addition to pre-prod
- Deploy main

We can base resources on pre-prod to start with.

### Additional Information

TBC: What domain should this be on?

### Definition of Done

- [x] Github actions includes production
- [x] Production environment is running and is protected by EntraID
- [ ] prod domain url

**Comment by LavMatt** [comment]
it was decided to leave the domain name as is for now - can be revisited if required at a later date
