### ISSUE TITLE
EntraID for prod

### ISSUE THREAD

**Issue by MatMoore** [ministryofjustice/find-moj-data#495]
Part of https://github.com/ministryofjustice/find-moj-data/issues/494

Configure EntraID for the new prod environment

Previous ticket:
https://github.com/ministryofjustice/find-moj-data/issues/212

**Comment by mitchdawson1982** [comment]
Awaiting permissions [approval](https://portal.azure.com/#blade/Microsoft_AAD_RegisteredApps/BrandingBlade/appId/ab70eeb4-b295-4c3b-9134-83f472856985/isMSAApp/) -
