### ISSUE TITLE
Deploy production instance of Find MOJ data

### ISSUE THREAD

**Issue by MatMoore** [ministryofjustice/find-moj-data#497]
Part of https://github.com/ministryofjustice/find-moj-data/issues/494

Once we have datahub running in prod, we can deploy Find MOJ data.

- [x] - Set up secrets & environment variables for prod
- [x] - Add prod to CI/CD workflow
- [ ] - Create a release in github (come up with a version number & release notes)
- [ ] - Creating a GH release approves the prod deployment
- [ ] - Deploy it

**Comment by mitchdawson1982** [comment]
- CP Prod Namespace [PR](https://github.com/ministryofjustice/cloud-platform-environments/pull/24316)

**Comment by mitchdawson1982** [comment]
Agreed to proceed with the workflow approaches laid out in this ticket -

**Comment by mitchdawson1982** [comment]
Workflow update required
