### ISSUE TITLE
Get ingestion running on prod

### ISSUE THREAD

**Issue by MatMoore** [ministryofjustice/find-moj-data#499]
Part of #494 

- ~~Create an IAM role so that we can run our ingestion from github actions (copy from preprod)~~ didn't realise but role exists for the repo useable by all envs
- Ingest CADeT and Justice Data
- **No EDSAs in prod please**
- ~~TBC: set up a schedule?~~

**Comment by LavMatt** [comment]
justice data source has been copied to data-catalogue repo and added to ingestion workflows https://github.com/ministryofjustice/data-catalogue/pull/201

**Comment by LavMatt** [comment]
ingestion workflows now working from gha ands have been used to populate prod datahub
