### ISSUE TITLE
Readable database name

### ISSUE THREAD

**Issue by seanprivett** [ministryofjustice/find-moj-data#510]
Analytics engineers requested a display name at database level (no underscores?) - The requirement should be clarified with Analytics engineers (think Phil Hall raised it) - i.e. whether it's more than just replacing underscores with spaces

https://mojdt.slack.com/archives/C03QZ776JVA/p1719228185070749

- We may need to display actual underlying name as well as display name so technical users know what to actually look for
- Should not negatively affect search (`example_database` - search for "example", "database" or "example_database" should all work)

**Comment by alex-vonfeldmann** [comment]
Design for review - search with clean table name and nice database name

![Image](https://github.com/ministryofjustice/find-moj-data/assets/115145706/779d9805-99e6-4c68-98f0-6c15f2c3077b)

**Comment by alex-vonfeldmann** [comment]
design for review: database page with both 

![Image](https://github.com/ministryofjustice/find-moj-data/assets/115145706/d092e2bb-af6e-439c-8b9e-dafdecd98c45)

nice name and technical name
