### ISSUE TITLE
Alter GA4 config to point at production front end

### ISSUE THREAD

**Issue by seanprivett** [ministryofjustice/find-moj-data#542]
- Change the data stream in our existing property https://analytics.google.com/analytics/web/#/a313689566p440738339/admin/streams/table/
- Make sure the environment variable with the property id is set in production
- Remove the environment variables from dev
- After deploying, you should be able to test that data is being received correctly from the data stream page

Note: there is an additional stream there for analytics coming from Datahub itself, but this is not enabled in any environments at the moment (switching it on requires us to build a custom docker image)

**Comment by MatMoore** [comment]
This is set up on prod and it looks like data is coming in for Find MOJ data. If there are no obvious issues before planning tomorrow, I'll move it done.

GA is set up to allow events from prod datahub as well, but this does not have the GA tags on the page, as doing so currently requires deploying a customised frontend image, and we haven't done that yet.
