### ISSUE TITLE
Implement funnel exploration on GA4

### ISSUE THREAD

**Issue by seanprivett** [ministryofjustice/find-moj-data#543]

**Comment by murdo-moj** [comment]
We agreed this is the wrong way round - start with the things useful to measure and then find a way to do that, rather than search GA for useful premade metrics.

**Comment by teeceeas** [comment]
**A user searching for and accessing a dataset**

 **Set Up Key Events in GA4**
   - **Log into Google Analytics 4** and navigate to your property.
   - If your desired events (e.g., "Dataset Searched", "Dataset Viewed", or "Download Started") are not already tracked, use **Google Tag Manager** to set up these events:
     - **Create Custom Events:** Go to **Configure > Events > Create Event**.
     - Add custom events like "Dataset Search Completed" or "Dataset Viewed".
   - You can also use **automatic events** in GA4 (e.g., page views, form submissions) if they match your needs.

**Define Conversions**
   - In GA4, **conversions** are used to track important actions. 
   - Go to **Configure > Conversions** and mark events (like "Dataset Viewed") as conversions.
   - For journeys, the conversion might represent a successful dataset discovery or interaction with relevant data.

**Set Up a Funnel Report**
   - Go to **Explore > Create New Exploration > Funnel Exploration**.
   - Set up the **steps in the user journey**. For example:
     1. **Step 1:** Search initiated (event: Dataset Search).
     2. **Step 2:** Dataset details viewed (event: Dataset Viewed).
     3. **Step 3:** Dataset downloaded or explored (event: Dataset Download Started).
   - This funnel will visualize how many users move through each step of the journey.

 **Configure Audience Segments**
   - Create audience segments to track different user groups:
     - **Users who completed the journey**.
     - **Users who dropped off at different points** in the journey.
   - Go to **Configure > Audiences > Create Audience** and define your audience based on event conditions.

**Create a Dashboard**
   - Go to **Reports > Library > Create New Dashboard** or use an existing template.
   - Add the following widgets to your dashboard:
     - **Funnel Visualization**: Shows the percentage of users moving through each step of the journey.
     - **Conversion Rate**: Displays the percentage of users who completed the journey.
     - **Drop-off Points**: Displays where users drop off in the journey.
     - **User Segments**: Break down users who completed or abandoned the journey.

**Set Up Goals or Alerts**
   - Set up **alerts** for when certain thresholds (e.g., low conversion rates) are hit.
   - Configure **goals** based on user completion rates or drop-off points.

**Monitor & Refine**
   - Use the dashboard regularly to monitor how users are progressing through the journey.
   - Refine your events, segments, or steps based on findings.

**Comment by LavMatt** [comment]
need to wait a day for the new events to be available to use in a funnel report

**Comment by LavMatt** [comment]
The funnel report appears very temperamental - displaying different completion rates depending on when it is looked at. Hoping this is just data settling after creating new events and it is more stable once events are established and have consistent data streaming through to GA4
