### ISSUE TITLE
Browse by domain improvements

### ISSUE THREAD

**Issue by seanprivett** [ministryofjustice/find-moj-data#560]
Only show domains which have data assets in the front end. Currently domains are listed with zero data assets, leading to a frustrating click.

Show data asset counts by each domain, as in the DataHub UI (maybe in brackets after the domain name?)

Also confirm whether there is a way to increase the number of facets returned (is currently 20). Can it be configured via the datahub deployment in a env var? Doesn't look like it can be increased via graphql input. If it can't be increased we will want to change how we are fetching the domains

**Comment by mitchdawson1982** [comment]
I have a very basic PR in flight, which displays the asset count in the front-end home page. 

![Image](https://github.com/user-attachments/assets/a0a74144-c6b1-4e65-9c43-b922debd41ff)

The key issue currently is that the facets search is unfiltered so it returns the number of assets assigned to a domain, however, we only want to display the number of assets for a given domain which have the `dc_display_in_catalogue` tag attached.
