### ISSUE TITLE
User guide: intro to the catalogue

### ISSUE THREAD

**Issue by seanprivett** [ministryofjustice/find-moj-data#564]
This is a paragraph overview of what the service does.

Looking at the cloud platform this involves a service agreement and lots of detail. https://user-guide.cloud-platform.service.justice.gov.uk/

A getting started section would be good. The amount of links on the homepage of CP feels very useful too.

**Comment by murdo-moj** [comment]
https://github.com/ministryofjustice/data-catalogue-user-guide/pull/7
