### ISSUE TITLE
Check requirement for cookie banner and statement

### ISSUE THREAD

**Issue by seanprivett** [ministryofjustice/find-moj-data#565]
### What the internet says:
> Do I need a cookie policy on my website?
> Yes, if your website uses cookies. GDPR and most other privacy laws require that you disclose to visitors what information you collect from them, such as their personal data and what you do with this information. If you use cookies to collect data from your site users, then you must have a cookie policy. 

### Asking the digital it forum
https://mojdt.slack.com/archives/C0282GUGKL7/p1722422636708839

>It's not the use of cookies, it's the fact that you are tracking and using information about user behaviour and interactions (albeit indirectly through Google Analytics, or indeed other third party components).
>The banner advises users that their activity and information might be recorded, and gives them the chance to opt-out before proceeding.

me:
>Is the opt-out here just to not use the service? For something like GA which doesn't tag stats to a particular user how would you provide the opt-out functionality?

>Basically, that's correct. If the user wants to use the service, part of that use is conditional on them accepting that their activity and information is being tracked. If they don't accept that condition, the only option for them is not to use the service.
While GA and other tracking/analytic tools do not explicitly tag for a given user (so they say), it is still possible to do other forms of correlation. [Browser fingerprinting](https://smartframe.io/blog/browser-fingerprinting-everything-you-need-to-know/) being just one example.

**Comment by murdo-moj** [comment]
Looks like we do need a banner to inform users of that we are and how we are profiling them to improve the service. I am not sure what form an opt-out would take other than taking them off the service.
