### ISSUE TITLE
Spike: Approach for assigning ownership to users that do not exist in datahub

### ISSUE THREAD

**Issue by LavMatt** [ministryofjustice/find-moj-data#578]
Now we are actually assigning some real owners of cadet data to entities via our dbt cadet ingestion some issues with the approach have surfaced

As a quick recap we ask users to add a custom metadata property in cadet `dc_owner` which we then map to entity ownership in datahub. We have requested the format of the `dc_owner` value be {firstname}.{lastname} as it appears in the persons justice email so if you had `jon.smith45@justice.gov.uk` the entry would be `dc_owner: jon.smith45`. see example [here](https://github.com/moj-analytical-services/create-a-derived-table/blob/main/mojap_derived_tables/dbt_project.yml#L41)

### Issues with the current approach
The current approach does not create a user entity in datahub, although it does create an urn and assign that urn as the owner for datasets. This creates an owner against a dataset, but that owner will have no other metadata associated with it (such as email) e.g:
![Image](https://github.com/user-attachments/assets/ae034c30-9aa3-4460-8e55-990c5370dfa3)
If you were to click on the user here you would be taken to an error screen saying the entity does not exist.

This resulted in a bug where we did not display info about an owner, where we opt to show an email address (because it didn't exist) - a fix for now can be seen in this PR https://github.com/ministryofjustice/find-moj-data/pull/580

It was hoped that because we have created the urn as it would be created via an sso sign, that it would map to a user created if/when they logged into datahub, however the datahub urns appear to be case sensitive. This means you can and likely will (when cases don;t match) have duplicated users - one that is assigned to a dataset as an owner and one created at first login that will not be associated with an owned datasets (and we already do actually have this scenario). 

This is likely to cause confusion and not help if/when we want to view ownership at the user level. e.g. i want to look at this person and see all the data that they are assigned owner of.

### What should the spike achieve
Investigate and document options for approaches that would better sync ownership with user entities as they are created in datahub - without needing for every owner to log into datahub to create their user. Any option(s) should aim to avoid the issues highlighted above.

**Comment by MatMoore** [comment]
Initial thoughts

- it's weird that the meta mapping does not generate an Owner entity if it is missing - find out if there is a reason for this or if we could submit a patch
- does it make any difference if we enter the whole user's email in the meta mapping? was there a reason we couldn't do that?
- we can create owners via the datahub cli
- long term, we would want a friendly ui for assigning data custodians, and it should be managed by data stewards. so this would make the meta mapping redundant anyway

**Comment by MatMoore** [comment]
This is the code that processes the meta mapping in the dbt ingestion
https://github.com/datahub-project/datahub/blob/84c677629d78a0644f667c3e0addac9fb28154ce/metadata-ingestion/src/datahub/utilities/mapping.py#L388

It could handle either Firstname.Lastname or Firstname.Lastname@domain.gov.uk as the user id.

Then it will map that to a URN like `urn:li:corpuser:{owner_id}`

However, users that log in to Datahub for the first time are getting an account created with the first part of their email address, and I don't think we can change it. So entering the whole email in the meta field will not help at all.
