### ISSUE TITLE
Enable horizontal scaling on FMD pods

### ISSUE THREAD

**Issue by jemnery** [ministryofjustice/find-moj-data#643]
https://user-guide.cloud-platform.service.justice.gov.uk/documentation/concepts/deploying.html#horizontal-pod-autoscaling-hpa

**Comment by MatMoore** [comment]
Our limitRange.defaultRequest.cpu is set to 10m

Currently the actual usage is 7m and 6m

**Comment by MatMoore** [comment]
The snippet in the docs is wrong

targetCPUtilizationPercentage only existed in v1 of this resource

https://stackoverflow.com/questions/41643709/kubernetes-autoscaler-targetcpuutilizationpercentage
