### ISSUE TITLE
Spike: investigate measurement of GraphQL queries

### ISSUE THREAD

**Issue by jemnery** [ministryofjustice/find-moj-data#644]
In order to optimise, first understand how we can measure the performance of GraphQL queries.

**Comment by MatMoore** [comment]
It seems like we have some information on this in Sentry. Here is an example trace https://ministryofjustice.sentry.io/performance/trace/3f61c9a2d01c4f75a7e700b43ee7e48d/?environment=prod&fov=0%2C605.52587890625&pageEnd&pageStart&query=span.op%3Ahttp.client&source=traces&statsPeriod=30d&timestamp=1726051121.802

**Comment by MatMoore** [comment]
I looked into whether django-silk added anything, but I found it a bit buggy and django debug toolbar works better for local development. There is a flamegraph panel we could try if we want to go beyond graphql: https://django-debug-toolbar.readthedocs.io/en/latest/panels.html#flame-graphs

Also, if we need to visualise cprofile output, we can use SnakeViz. Example:

 ![Image](https://github.com/user-attachments/assets/ef46363c-f319-4421-b8bf-33405a3cc030)

**Comment by MatMoore** [comment]
From the Datahub side, we can look at what the GraphQL controller is doing via kibana

https://kibana.cloud-platform.service.justice.gov.uk/_plugin/kibana/app/discover#/view/b0ce5d70-75a6-11ef-8d2c-d115d24d0914?_g=(filters%3A!()%2CrefreshInterval%3A(pause%3A!t%2Cvalue%3A0)%2Ctime%3A(from%3Anow-15m%2Cto%3Anow))

**Comment by MatMoore** [comment]
## Debugging notes

I suspect listDomains is slow because we have an N+1 query problem on the backend

we are running

```graphql
query getDomains {
listDomains(
    input: {start: 0, count: 1000}
) {
  domains{
    urn
    properties{
      name
    }
    entities(
      input:{query:"*",start:0,count: 0, filters: [{field: "tags", values: ["urn:li:tag:dc_display_in_catalogue"]}]}
    ){
      total
    }
  }
}
}
```

which takes ~500ms. Without entities it's ~100ms.

Also need to check the caching behaviour. We are expecting the results of this query to be stored in Find MoJ data's cache.

**Comment by MatMoore** [comment]
## Alternate list domain query

This query is ~100ms

```graphql
{
  aggregateAcrossEntities(
    input: {
      query: "*"
      facets: ["domains"]
      orFilters: [{ and: [{ field: "tags", values: ["urn:li:tag:dc_display_in_catalogue"] }] }]
    }
  ) {
    facets {
      field
      displayName
      aggregations {
        value
        count
        entity {
          urn
          ... on Domain {
            properties {
              name
            }
          }
        }
      }
    }
  }
}
```

Differences from the listDomains query

- excludes domains with 0 entities in them
- includes phantom domains that are quasi-deleted but still have entities in them, e.g. https://datahub-catalogue-preprod.apps.live.cloud-platform.service.justice.gov.uk/domain/urn:li:domain:Date/Entities?is_lineage_mode=false

The latter case is detectable as it has null properties.

**Comment by MatMoore** [comment]
## Combined query

This takes ~150ms and will return all domains. The second part returns the counts.

```graphql
{
  listDomains(input: { start: 0, count: 1000 }) {
    domains {
      urn
      properties {
        name
      }
    }
  }
  aggregateAcrossEntities(
    input: {
      query: "*"
      facets: ["domains"]
      orFilters: [{ and: [{ field: "tags", values: ["urn:li:tag:dc_display_in_catalogue"] }] }]
    }
  ) {
    facets {
      field
      displayName
      aggregations {
        value
        count
      }
    }
  }
}
```

**Comment by MatMoore** [comment]
## Next steps
- [ ] https://github.com/ministryofjustice/find-moj-data/issues/856
- [ ] Check whether the domain list is cached properly
- [ ] Set DATAHUB_TELEMETRY_ENABLED=0 to avoid unnecessary queries
