### ISSUE TITLE
HTTP compression

### ISSUE THREAD

**Issue by jemnery** [ministryofjustice/find-moj-data#645]
We may gain a small performance benefit from enabling HTTP compression.

From Mat M: 

> I just checked and production doesn't have compression enabled. If we configure it in on the kubernetes ingress we can use brotli compression https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/configmap/#enable-brotli

There's an equivalent for gzip - `use-gzip` and `gzip-level`

**Comment by mitchdawson1982** [comment]
I have selected brotli level 6 which yields a 3/1 compression ratio and a 5% improvement over standard gzip [performance](https://www.debugbear.com/blog/http-compression-gzip-brotli).

**Comment by mitchdawson1982** [comment]
Cloud platform have confirmed that this isn't going to be possible with the way that they apply their ingress configuration.  We could perform compression in Django using [gzip](https://docs.djangoproject.com/en/5.1/ref/middleware/#module-django.middleware.gzip)
