### ISSUE TITLE
🚄 Optimize CaDeT ingestion pipeline

### ISSUE THREAD

**Issue by MatMoore** [ministryofjustice/find-moj-data#655]
### User Story

Reduce the CaDeT ingestion time to < 1h so that we are able to run it multiple times a day if we need to (e.g. for debugging).

### Value / Purpose

The cadet ingestion workflow includes the following steps:

"create cadet domains" 2m 48s
- `__init__` 0s
- get_workunits 2m 37s
  - get_cadet_mainfest 2m 37s
  - _get_databases_with_domains_and_display_tags 0s

"push metadata to datahub" 3h 11m 32s
 - `__init__` 0s
 - get_workunits 2m 27s
   - _get_cadet_manifest 2m 36s
   - _get_domain_mapping 0s
   - **AssignCadetDomains transformer 2h 32m 10s**
   - AssignCadetDatabases 2m 42s
     - get_cadet_manifest 2m 41s
     - _get_table_database_mappings 0s

So over 2h of the 3h job is spent in in our custom transformer. This really slows down the feedback loop when changing things.

### Hypothesis

This code scales poorly because if there are N nodes being transformed, we create N regular expressions, and then for every node, we loop over the N regexes, so the runtime is N^2.

https://github.com/ministryofjustice/data-catalogue/blob/35917141502c151b94e0bbacb508e19b68ec4e93/ingestion/transformers/assign_cadet_domains.py#L77

### Proposal

<strike>We should instead create 1 regex per domain. If that is not possible, then we can always inherit from the base transformer instead of this regex one.

Additional optimisations may be possible, e.g. downloading the cadet manifest only once, and sharing it between the sources/transformers.</strike>

See Matt's branch below

### Definition of Done

- [ ] Ingestion takes < 1h

**Comment by LavMatt** [comment]
I tried this out very quickly as an alternative approach not using a transformer at all - it got it down to ~45 mins https://github.com/ministryofjustice/data-catalogue/compare/main...optimise-domain-assignment

**Comment by murdo-moj** [comment]
https://github.com/ministryofjustice/data-catalogue/pull/259
