### ISSUE TITLE
Spike: taxonomy and searching

### ISSUE THREAD

**Issue by seanprivett** [ministryofjustice/find-moj-data#659]
To expand on how people search by domain/subject area: how do we make things easy to find?

Subdomains as part of domains (eg HMPPS, then prison, probation, etc.) was received very well in user research

**Comment by seanprivett** [comment]
Firstly, collate list of early adopters and the data sets as they exist now outside the catalogue. Use this to gather source material for the card sort. We'll use the specialist tool that Jess mentioned. This type of exercise requires at least 30 people to take part. We should recruit both data and analysis specialists and more generalist users beyond the analytical community.

Early adopter datasets:

ESDA
Data First
DPR
Electronic Monitoring
Create a derived table
Justice Data
MOJ publications
Planet FM

**Comment by jessicajsmith** [comment]
Jess to request setting up an account: https://www.optimalworkshop.com/?utm_source=google&utm_medium=cpc&utm_campaign=search_ukie_brand&keyword=optimal%20workshop&matchtype=e&network=g&gad_source=1&gclid=Cj0KCQjw8MG1BhCoARIsAHxSiQl-KLXjZs0sqBjCdSb-VS8uo5DYEU5QiSxkdAXlt2WHOLZRTTgAEHsaAnrNEALw_wcB
