### ISSUE TITLE
Customise `Sorry, there is a problem with the service` error page

### ISSUE THREAD

**Issue by LavMatt** [ministryofjustice/find-moj-data#666]
### User Story

As a user of the catalogue
I expect to have appropriately worded error screens
So that i'm not confused

### Value / Purpose

Currently when the service is unavailable we are using the standard CP template and message for this error screen

![Image](https://github.com/user-attachments/assets/1483b482-c418-4322-a5a3-cc35657d6905)

However the wording is not appropriate for the find-moj-data service

### Hypothesis

If we... [do a thing]
Then... [this will happen]

### Proposal

Follow the instructions here to create a custom error page for this https://runbooks.cloud-platform.service.justice.gov.uk/custom-default-backend.html#custom-default-backend

### Definition of Done

Example - [ ] Documentation has been written / updated
- [ ] README has been updated
- [ ] User docs have been updated
- [ ] Another team member has reviewed
- [ ] Tests are green

**Comment by markjefferson-gov** [comment]
Hi @LavMatt . Is this the 404 for https://find-moj-data.service.justice.gov.uk/ or something else?

**Comment by murdo-moj** [comment]
Hi Mark, its for something else.

We control and have custom error pages for 400 bad request, 404 not found, and 500 internal server errors on https://find-moj-data.service.justice.gov.uk/. This ticket is to implement custom error pages for other errors to do with not being able to reach our app eg 502 Bad Gateway, 503 Service Unavailable, and 504 Gateway Timeout.

**Comment by markjefferson-gov** [comment]
@murdo-moj Thanks Murdo. 

I would typically expect all the server error pages to look the same - assuming the implications for the user are the same. e.g:

[H1] Sorry, there is a problem with the service
Try again later.
If the problem persists, contact us... etc.

What does the 500 error look like?

**Comment by murdo-moj** [comment]
500

![Image](https://github.com/user-attachments/assets/2fbd8c9b-da8f-4bc7-8bd1-328a304f49ac)

500 datahub unavailable (as devs it's useful for us to know if it's datahub or the app giving us problems)

![Image](https://github.com/user-attachments/assets/8829fb69-d558-4ed1-aa7d-f1ddde691a9d)

**Comment by murdo-moj** [comment]
https://mojdt.slack.com/archives/C57UPMZLY/p1724752941516249 I have asked CP to change the default. They got it from the formbuilder service which explains the copy about answers being saved

**Comment by murdo-moj** [comment]
I raised an issue with CP, they'll pick it up at some point https://github.com/ministryofjustice/cloud-platform/issues/6084

**Comment by murdo-moj** [comment]
#726 I have made those copy changes for you
