### ISSUE TITLE
♻ [Placeholder] Add back subdomain support

### ISSUE THREAD

**Issue by MatMoore** [ministryofjustice/find-moj-data#720]
Datahub supports arbitrarily nested domains.

In earlier versions of Find MoJ data we showed 2 levels: *domain* and *subdomain*. This allowed us to organise metadata first by organisational unit (e.g. HMCTS) and then have finer grained subject areas within each one (e.g. different kinds of courts)

Later, we swapped this out for a single-level domain model. However, since this is not testing well, and Scottish Gov have also mentioned using subdomains, I'm proposing we add subdomains back again in some form. 

This is a placeholder ticket to record what needs doing if/when we revisit this.

## Value of a hierarchical filter
- we can restrict the top level subject area to a small number to avoid overwhelming users with choice
- it allows the user to be either vague or specific when filtering by subject area

## Current design: filter by top level domain
<img width="266" alt="Screenshot 2024-08-27 at 11 08 27" src="https://github.com/user-attachments/assets/44fb8305-4adc-4700-b1ee-52fa6fdfcca0">
<img width="316" alt="Screenshot 2024-08-27 at 11 00 14" src="https://github.com/user-attachments/assets/18d99be6-d5f4-43cd-808b-868259e6b7a8">
<img width="261" alt="Screenshot 2024-08-27 at 11 08 39" src="https://github.com/user-attachments/assets/eec4f2dd-7a45-4f86-b883-a3b531073dad">

### Behaviour
- there is a single list of options
- domains only get displayed as an options if they are top-level
- if subdomains are used, certain entities will be inaccessible by browse / filtered search 
  - this behaviour was introduced when we switched to the `listDomains` query, which excludes subdomains (https://github.com/ministryofjustice/find-moj-data/pull/597)
  - version b513e90 includes subdomains but doesn't display counts on the homepage

## Previous design: Domain/Subdomain
<img width="292" alt="Screenshot 2024-08-27 at 11 26 54" src="https://github.com/user-attachments/assets/e502add3-6cb2-4747-ac7c-56228e6a97c4">
<img width="288" alt="Screenshot 2024-08-27 at 11 27 09" src="https://github.com/user-attachments/assets/a6aa131e-ba90-4ce2-87ff-80784460aad6">
<img width="295" alt="Screenshot 2024-08-27 at 11 26 45" src="https://github.com/user-attachments/assets/7d912ee8-00f9-4202-bdf9-019b3f5c89ce">

### Behaviour
- if the user selects only the top level domain, the results include entities assigned to that domain or any of its subdomains
  - this relies on code that has since been removed: https://github.com/ministryofjustice/find-moj-data/blob/bc02e954b3e98a9de70cca606d22a000b87cafc8/home/service/search.py#L22 
- users can refine the search further by choosing a subdomain
- if datahub contains sub-sub-domains, these get ignored in the frontend
  - but entities are still accessible when filtering on the domain/subdomain
- javascript for this component is here: https://github.com/ministryofjustice/find-moj-data/blob/main/static/assets/js/enhanced-search.js 
  - if javascript is not available, then only the top level filter is shown

## Definition of Done

- [ ] Decided what to call the subdomain field
- [ ] Decided whether to change the home page list
- [ ] Added a feature toggle and documented in README
- [ ] Updated the user guide
- [ ] Ensured the tests cover with and without the feature flag

**Comment by markjefferson-gov** [comment]
Relates to [Spike: taxonomy and searching](https://github.com/orgs/ministryofjustice/projects/57/views/20?pane=issue&itemId=74221601).
