### ISSUE TITLE
Content changes to Runbook-based user guide

### ISSUE THREAD

**Issue by seanprivett** [ministryofjustice/find-moj-data#749]
As a Content designer, I want to improve some descriptions in the content of the user guide version A and replace the version on find MoJ data(B) with the version on the runbook(A) so that it reflects the version users prefer

**Acceptance Criteria**

- Create one version of CaDeT user guidance to sit within Find MoJ Data - use doc A as the master (the version that currently sits in the runbook - we will move it to the user guide once the content is sorted)
Doc A = runbook version
Doc B = user guide version

- Titled 'Adding tables to Find MoJ Data from Create-A-Derived-Table (CaDeT)  - replace title doc a with title doc b
- Consistency of how MoJ acronym is displayed MoJ - lower case o should be used and small d for data
- Take first bullet point para from doc b and put as first para in first section of doc A
- Config of cadet models link in 3rd bullet point of doc B, place this after the 'dc_display_in_catalogue' tag. text in doc A
- Take full example from doc B and include this after the additional metadata section doc A
- Ensure consistency of terms - e.g. reference Find MoJ data instead of 'the catalogue'
- Add links to Slack and Teams channel to last para 'Speak to the data catalogue...' 
- Replace the version on find MoJ data(B) with the version on the runbook(A)

For more info - https://miro.com/app/board/uXjVKZ30W-c=/?moveToWidget=3458764598413662797&cot=14

**Comment by murdo-moj** [comment]
https://github.com/ministryofjustice/find-moj-data-user-guide/pull/15
