### ISSUE TITLE
Additional content needed for user guide

### ISSUE THREAD

**Issue by seanprivett** [ministryofjustice/find-moj-data#751]
As a Content designer, I want to improve some descriptions in the content of the user guide version A, so that it is clearer to users

**Acceptance Criteria**

- Provide an explanation on what would happen if you don't set metadata at the domain level and why it's recommended (ask Matt L)
- Replace the word enum or review whole example (maybe ask Mark)

For more Info: https://miro.com/app/board/uXjVKZ30W-c=/?moveToWidget=3458764598413662797&cot=14

**Comment by teeceeas** [comment]
![Screenshot 2024-09-09 at 16 03 04](https://github.com/user-attachments/assets/0bd36fb0-7b19-4607-82fc-ff440abb57b1)

![Screenshot 2024-09-09 at 16 05 22](https://github.com/user-attachments/assets/bdf68feb-1e26-4de0-a02c-205901acea15)
