### ISSUE TITLE
Appsec action: deployment.yml securityContext settings

### ISSUE THREAD

**Issue by jemnery** [ministryofjustice/find-moj-data#764]
Container 'find-moj-data' of Deployment 'find-moj-data-deployment' should set `securityContext.readOnlyRootFilesystem` to `true`

(An immutable root file system prevents applications from writing to their local disk. This can limit intrusions, as attackers will not be able to tamper with the file system or write foreign executables to disk)

See https://avd.aquasec.com/misconfig/ksv014 

---

Container 'find-moj-data' of Deployment 'find-moj-data-deployment' should set `securityContext.allowPrivilegeEscalation` to `false`

(A program inside the container can elevate its own privileges and run as root, which might give the program control over the container and node)

See https://avd.aquasec.com/misconfig/ksv001 

---

Container 'find-moj-data' of Deployment 'find-moj-data-deployment' should set `securityContext.runAsNonRoot` to `true`

(Force the running image to run as a non-root user to ensure least privileges)

See https://avd.aquasec.com/misconfig/ksv012 

---

Container "find-moj-data" of deployment "find-moj-data-deployment" in "default" namespace should specify a seccomp profile 

(A program inside the container can bypass Seccomp protection policies)

See https://avd.aquasec.com/misconfig/ksv104 

---

- [ ] set 'securityContext.readOnlyRootFilesystem' to true
- [ ] set 'securityContext.allowPrivilegeEscalation' to false
- [ ] set 'securityContext.runAsNonRoot' to true
- [ ] specify a seccomp profile 
- [ ] Regression testing - does `readOnlyRootFilesystem` or `seccompProfile RuntimeDefault` break anything? (privilege escalation and running as root shouldn't be required 😬 )

**Comment by jemnery** [comment]
Examples

```yaml
spec:
  [...]
  template:
    [...]
    spec:
      [...]
      containers:
        - name: find-moj-data
          [...]
            seccompProfile:
              type: RuntimeDefault
```

**Comment by murdo-moj** [comment]
https://github.com/ministryofjustice/find-moj-data/pull/767
