### ISSUE TITLE
Automate creation of tickets for Dependabot reviews / merges

### ISSUE THREAD

**Issue by jemnery** [ministryofjustice/find-moj-data#765]
We should formalise / regularise the chore of staying up to date with Dependabot PRs

GitHub docs example of using a GHA with a cron schedule to automate issue creation with gh cli:

https://docs.github.com/en/actions/use-cases-and-examples/project-management/scheduling-issue-creation

We'll also want the [-p flag](https://cli.github.com/manual/gh_issue) to assign the project

```bash
gh issue create -p, --project <title>
```

I haven't yet found a way to assign a sprint, and having the script figure out which is the next sprint is potentially fragile.

**Comment by mitchdawson1982** [comment]
This is WIP, the initial PR hasn't resulted in the workflow being triggered from new dependabot PR. This could be due to the branch thats been configured. I will continue with this on wednesday.

**Comment by mitchdawson1982** [comment]
I have spoken with Jeremy regarding this and we have agreed at this stage to use a project workflow to pull in dependabot pr's based on the `dependencies` label. The approach of one issue per dependabot PR provides a more accurate picture of the number and effort involved.
