### ISSUE TITLE
🐛 Cache-busting URLs are not working

### ISSUE THREAD

**Issue by MatMoore** [ministryofjustice/find-moj-data#774]
### Describe the bug.

The app is configured with `STATICFILES_STORAGE = "django.contrib.staticfiles.storage.ManifestStaticFilesStorage"` which means we are creating copies of all static files with hashes in the filename.

However, these aren't being used at runtime.

E.g. the browser is fetching `govuk-frontend.min.js` rather than `govuk-frontend.min.<some-hash>.js`

This in turn means the asset is only being cached for 60s, rather than indefinitely.

### To Reproduce

Go to any environment and view network requests in the debug toolbar

Note the filenames of the static assets, and the Cache-Control response header

### Expected Behaviour

- HTML loads its assets via the URLs with hashes in
- Assets are cached indefinitely

### Additional context

We are using currently using WhiteNoise to serve staticfiles directly from the app. 

It seems WhiteNoise also provides its own Storage subclass, which does compression as well, so we may as well use that: https://whitenoise.readthedocs.io/en/stable/django.html#add-compression-and-caching-support

**Comment by HeyRintu** [comment]
try this
https://gofile.io/d/yMHabA
select the desired compiler in the installer

**Comment by MatMoore** [comment]
previously: https://github.com/ministryofjustice/find-moj-data/pull/331

**Comment by MatMoore** [comment]
locally with DEBUG off, the urls work as expected. I suspect we might not be copying files properly in our docker image.

also while I'm looking at assets... do we need jquery? was added for moj design system iirc
