### ISSUE TITLE
🐛 quoted search not working on preprod

### ISSUE THREAD

**Issue by MatMoore** [ministryofjustice/find-moj-data#783]
### Describe the bug.

prod is working, preprod returns no matches for a quoted search, e.g. "Common platform"

this is after updating datahub 

see https://datahubproject.io/docs/releases/#v0-14-0-2

**Comment by mitchdawson1982** [comment]
Whilst reviewing the current behaviour I happened to notice that the double quoted search term was surrounded by additional double quotes in the response message. 

![Image](https://github.com/user-attachments/assets/aaec9b5a-15bd-48f1-9de3-27e62653d735)

**Comment by mitchdawson1982** [comment]
Testing local FMD against dev DH with query fix removed i.e.
`# query = form_data.get("query", "").replace("_", " ")
        query = form_data.get("query", "")`

**Comment by mitchdawson1982** [comment]
It looks as though search behaviour has been changed in the latest [datahub](https://github.com/datahub-project/datahub/pull/10690) version where if search terms contain quotes, underscores or full-stops then they are treated as exact matches.

```
# Criteria for exact-match only
  # Contains quotes, is a single term with `_`, `.`, or `-` (normally consider for tokenization) then use exact match query
  - queryRegex: >-
      ^["'].+["']$|^[a-zA-Z0-9]\S+[_.-]\S+[a-zA-Z0-9]$
    simpleQuery: false
    prefixMatchQuery: false
    exactMatchQuery: true
```
