### ISSUE TITLE
Show data sources from CaDeT ingestion in find-moj-data

### ISSUE THREAD

**Issue by murdo-moj** [ministryofjustice/find-moj-data#797]
[We currently ingest dbt sources from CaDeT](https://github.com/ministryofjustice/data-catalogue/blob/2e59cfb6c08c2b0e8de4cafd30c5bb97b782520a/ingestion/cadet.yaml#L27)

However, these are excluded from find-moj-data, as [only models have the `dc_display_in_catalogue` tag](https://github.com/ministryofjustice/data-catalogue/blob/2e59cfb6c08c2b0e8de4cafd30c5bb97b782520a/ingestion/create_cadet_databases_source/source.py#L138)

We've got some concerns about if sources can be included in the catalogue, as some data owners consider metadata information to be sensitive. We might have to add an exceptions list for some sources.

- NOMIS metadata is commercially sensitive, it's not wanted to be on the data marketplace.
- No counter terrorism data should be included
- How much metadata about sources is even on CaDeT?

**Comment by MatMoore** [comment]
dbt docs on sources https://docs.getdbt.com/docs/build/sources

CaDeT does make use of this: https://github.com/moj-analytical-services/create-a-derived-table/tree/main/mojap_derived_tables/models/sources

who makes the call on what is sensitive or not?

**Comment by MatMoore** [comment]
we have sources enabled already in the ingestion, we just aren't adding the display in catalogue tag

**Comment by MatMoore** [comment]
list of sources we are talking about

```
alpha_vcms_data
avature_scraper
bold_essex_police_data
bold_essex_police_data_dev
bold_rr_case_info_dashboard_dev
bold_rr_case_info_dashboard_prod
calculate_release_dates_api_dev
calculate_release_dates_api_prod
caseman_derived_dev_v1
caseman_dev_v1
ccd_dev_sdp_probate_test_2
ccd_dev_sdp_test
ccd_dev_sdp_test_v3_probate
ccd_dev_sdp_v1
ccd_dev_test
ccd_v1
common_platform_dev_sdp_v3
common_platform_dev_v4
contracts
corporate_ctm
corporate_my_learning
corporate_sop
data_eng_uploader_prod_calc_release_dates
data_eng_uploader_prod_cstr_phase_two
data_eng_uploader_prod_hyperion_dummy
data_eng_uploader_prod_hyperion_finance
data_eng_uploader_prod_lookup_finance
data_eng_uploader_prod_lookup_finance_dummy
data_eng_uploader_prod_ppud_dev
data_eng_uploader_prod_ppud_prod
data_eng_uploader_prod_property_planetfm
data_eng_uploader_prod_sop_finance
data_eng_uploader_prod_sop_finance_dummy
data_eng_uploader_prod_subject_access_requests
data_linking
data_linking_anonymised
data_linking_data_first
delius
derived_xhibit_beta
electronic_monitoring_service
example_postcodes_db
familyman_derived_live_v4
familyman_dev_v3
familyman_live_v4
fines_enforcement_redacted_v2
fines_enforcement_v2
geog_addressbase_dev
geog_addressbase_prod
geog_nspl_reference_prod
geog_ons_lookups_prod
hmlr_price_paid
hmpps_adjustments_api_prod
hmpps_court_case_prod
hmpps_interventions_prod
hmpps_performance_hub_prod
hmpps_use_of_force_prod
hpc_staging
laa
lookup_offence_legacy
lookup_offence_raw
mags_curated_v2
mags_curated_v3
matrix_preprod
nomis
nomis_ao_historic
nomis_sens
oasys
oleeo_legacy_staging
opg_investigations_prod
opg_sirius_prod
opg_sop_prod
opg_sra_prod
opg_surveys_prod
pcol_derived_temp
pcol_dev_v1
prisons_ds
sop_derived
sop_lookups
sop_preprocessed
sop_remuneration_preprod
test_db
test_hudi_database
test_iceberg_database
viper
xhibit_der_v2
xhibit_v1
xhibit_v1_fix
```

I will exclude all the test ones.

None of these have table level descriptions, so this metadata is not very complete at the moment, but I'm going to focus on getting these entries into the catalogue first.

**Comment by MatMoore** [comment]
Need to see how these come through with an example. Unlike models, source metadata contains a database name and table names. **Does datahub create the database under the DBT platform or the Athena platform?**

**Comment by MatMoore** [comment]
Here's the above example on test

https://test.find-moj-data.service.justice.gov.uk/details/table/urn:li:dataset:(urn:li:dataPlatform:dbt,cadet.awsdatacatalog.data_eng_uploader_prod_calc_release_dates.survey_data,PROD)

It renders, but it takes 11s to do so.

**Comment by MatMoore** [comment]
PRs to revise the list of sources:

https://github.com/moj-analytical-services/create-a-derived-table/pull/2108
https://github.com/ministryofjustice/data-catalogue/pull/267

**Comment by MatMoore** [comment]
Draft PR for changing the tag override semantics -  https://github.com/ministryofjustice/data-catalogue/pull/270

This may or may not be required for tag deletions to be reflected in the scheduled ingestions. Will follow up on monday.

**Comment by LavMatt** [comment]
Following a meeting with Gwion in data engineering it is now understood that sources as in the current DE process relate to a raw version of data that we don't want to surface in find moj data. 

The Athena dbs and tables for analytical use, (clones of nomis, oasys, etc), are actually created with versioning logic (SCD2) from the raw sources via a python script in cadet, and are classed as models within dbt. However they are only created within a github actions environment and do not persist as model files within the create a derived table rep, so we require a different method to apply display tags to those databases and tables that are wanted to be displayed in find-moj-data.

We will remove the tags on all dbt sources and there is now a new issue to implement the ingestion of the curated layer of data as described above https://github.com/ministryofjustice/find-moj-data/issues/862
