### ISSUE TITLE
Get false positive alerts under control

### ISSUE THREAD

**Issue by YvanMOJdigital** [ministryofjustice/find-moj-data#832]
Our alerts channel is very busy right now due to some prometheus alerts getting triggered a lot:
[GMSCpuUsageHigh](https://alertmanager.live.cloud-platform.service.justice.gov.uk/#/alerts?receiver=slack-datahub_preprod)
[RDSLowStorage](https://alertmanager.live.cloud-platform.service.justice.gov.uk/#/alerts?receiver=slack-datahub_preprod)
[ElasticSearchClusterFreeStorageSpace](https://alertmanager.live.cloud-platform.service.justice.gov.uk/#/alerts?receiver=slack-datahub_preprod)

These [alerts](https://github.com/ministryofjustice/cloud-platform-environments/blob/main/namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-find-moj-data-dev/05-prometheusrule.yaml) might signify a problem, or they might be overly conservative and need loosening.

**Comment by teeceeas** [comment]
Find out what is causing the problem and raise bugs to resolve any issues that could be triggering the alerts

**Comment by MatMoore** [comment]
## Latency alerts
- We already bumped the threshold, and made some performance improvements
- The expression can divide by zero, which causes intermittent alerts. Workaround here: https://github.com/ministryofjustice/cloud-platform-environments/pull/26417

## Elasticsearch cluster free storage space
- Perhaps increase the duration threshold since this varies a lot

## RDS low storage (datahub)


## GMS CPU usage
- Maybe stop alerting on this. There is no practical action we should be taking if this is high, and request latency of GraphQL requests is a more relevant measure.

**Comment by MatMoore** [comment]
This one is still awaiting review https://github.com/ministryofjustice/cloud-platform-environments/pull/26417

The others I haven't been able to investigate any further yet.

Also, jn the process of following https://runbooks.cloud-platform.service.justice.gov.uk/debugging-aws-console-access.html I removed the data-platform-labs team, thinking it wasn't in use anymore, but this is still in use by the Find MoJ data cloud platform namespaces, so access (and potentially deployments) is broken at the moment. Cloud platform have said they should be able to fix this tomorrow (https://mojdt.slack.com/archives/C57UPMZLY/p1727794576675889)

**Comment by MatMoore** [comment]
Another issue here is that the runbook link on all the alerts doesn't work, so the alerts are not actionable. We should create runbook pages for each alert we want to keep, so that whoever is on support can easily respond to issues.

**Comment by MatMoore** [comment]
[KubeDeploymentReplicasMismatch](https://alertmanager.live.cloud-platform.service.justice.gov.uk/#/alerts?receiver=slack-datahub_test)

Fired today with

      - alertname: KubeDeploymentReplicasMismatch
      - clusterName: live
      - container: kube-state-metrics
      - deployment: datahub-acryl-datahub-actions
      - endpoint: http
      - instance: 172.20.175.1:8080
      - job: kube-state-metrics
      - namespace: data-platform-datahub-catalogue-test
      - pod: prometheus-operator-kube-state-metrics-6dd868784f-kdqdd
      - prometheus: monitoring/prometheus-operator-kube-p-prometheus
      - service: prometheus-operator-kube-state-metrics
      - severity: datahub_test

Expression

`kube_deployment_spec_replicas{job="kube-state-metrics",namespace="data-platform-datahub-catalogue-test"} != kube_deployment_status_replicas_available{job="kube-state-metrics",namespace="data-platform-datahub-catalogue-test"}`

This compares 
- kube_deployment_spec_replicas "Number of desired pods for a deployment."
- kube_deployment_status_replicas_available "The number of available replicas per deployment."

How do we debug this?

- go into k9s
- navigate to the namespace, then deployments
- the missing thing is in yellow with ready 0/0
- there are no logs

**Comment by MatMoore** [comment]
Configuration for datahub actions service accounts

`serviceAccount.create` defaults to false

`acryl-datahub-actions.serviceAccount.name` is set to ""

Service account name comes from `acryl-datahub-actions.serviceAccountName`
https://github.com/acryldata/datahub-helm/blob/58648eb8479ccbe789f7aa391b7bc633276d0c2e/charts/datahub/subcharts/acryl-datahub-actions/templates/deployment.yaml#L37

this seems to evaluate to default
https://github.com/acryldata/datahub-helm/blob/58648eb8479ccbe789f7aa391b7bc633276d0c2e/charts/datahub/subcharts/acryl-datahub-actions/templates/_helpers.tpl#L57

...so why is it looking for `data-platform-test`?

**Comment by MatMoore** [comment]
https://github.com/ministryofjustice/cloud-platform-environments/pull/26657

**Comment by MatMoore** [comment]
https://github.com/ministryofjustice/data-catalogue/actions/runs/11218554264 this one needs rolling out to prod still

**Comment by mitchdawson1982** [comment]
I have increased the evaluation period from 1 to 5 minutes for the Elasticsearch cluster free storage space alert

https://github.com/ministryofjustice/cloud-platform-environments/pull/26677
https://github.com/ministryofjustice/cloud-platform-environments/pull/26678
https://github.com/ministryofjustice/cloud-platform-environments/pull/26679
https://github.com/ministryofjustice/cloud-platform-environments/pull/26680

**Comment by MatMoore** [comment]
- [ ] RDS one needs to be rolled out to dev and preprod
- [ ] GMS one dev, preprod, prod
- [ ] Raise ticket for fixing alert links
- [ ] Latency fix dev, test, preprod

**Comment by MatMoore** [comment]
We should maybe also include the environment in the alert name to be clear

At the moment it's buried in the details so you can't see what environment it's for unless you click "show more" in the slack alert.

**Comment by MatMoore** [comment]
Follow up tickets:

- https://github.com/ministryofjustice/find-moj-data/issues/932
- https://github.com/ministryofjustice/find-moj-data/issues/933
