### ISSUE TITLE
SPIKE: How to ingest performance hub metrics/should we

### ISSUE THREAD

**Issue by jemnery** [ministryofjustice/find-moj-data#833]
What's the best way todo this? CSV upload? Push via CLI script? Custom ingester?

What entity type in datahub would metrcis map to?

**Comment by murdo-moj** [comment]
* Performance hub portal is hosted on modernisation platform
* Reasonable amount of metadata, not all the same fields as we currently have
* Backend is an RDS and .NET framework
* Performance hub accounts gives access to all metrics in one area (Prison, probation etc)
* No automated signup, just a mailbox to get an account
* It contains metrics collated from excel uploaded to the portal 
* Metrics have name and descriptions and source but not any owners (we have mailboxes)
* Metrics are grouped into areas
* 100k page views per month from mid level people reporting upwards
* Metrics on performance hub are unpublished


* Policy group was going to email around all the prisons in the UK asking for some data as they didn't know it was on performance hub - find MoJ data would allow them to serach for metrics easily.
*  The portal can export an excel of all the metrics and the metadata we'd want to expose to users. We could work to ingest this on the catalogue.
* We suggest a manual one time upload as a direct link is hard to get from RDS, as there's no API and the RDS had sensitive info on. Metrics are updated semi regularly but a future version of the portal built in the next few years would likely have an API for a more seamless ingestion. This seems good enough for now.
