### ISSUE TITLE
UCD: consider how to use data sources in Find MoJ data

### ISSUE THREAD

**Issue by markjefferson-gov** [ministryofjustice/find-moj-data#836]
Data sources will be available in Find MoJ data when this ticket is complete: https://github.com/orgs/ministryofjustice/projects/57/views/5?pane=issue&itemId=79103619 

We need to consider the user needs for this info and determine: 

* whether and how to show data sources on data entries, e.g. as labels or tags
* whether and how to show data sources in search results
* whether data source should be a filter

**Comment by teeceeas** [comment]
Filter by source system (does this mean anything to users)
Field to distinguish between source data and metadata directly from the end systems to distinguish in a case of duplication

**Comment by teeceeas** [comment]
Closed source data it is displayed as any other dataset on FMD
