### ISSUE TITLE
🐛 Header - org name should link to home

### ISSUE THREAD

**Issue by markjefferson-gov** [ministryofjustice/find-moj-data#838]
In the header, the organisation name ("Ministry of Justice") appears to be a link but doesn't go anywhere: 
![Image](https://github.com/user-attachments/assets/860c65eb-2f08-4b66-8d6c-68c2e1359893)

It should be part of the link to home along with the service name ("Find MoJ data"). See e.g. the [MoJ Design System](https://design-patterns.service.justice.gov.uk/) header.

**Comment by murdo-moj** [comment]
https://github.com/ministryofjustice/find-moj-data/pull/849
