### ISSUE TITLE
🐛 Bug on the Justice Data dashboard

### ISSUE THREAD

**Issue by markjefferson-gov** [ministryofjustice/find-moj-data#855]
2 rows are missing cells in the third column. The links to chart details are in the description instead. There also appears to be duplicate links with no text in the descriptions. 

![Image](https://github.com/user-attachments/assets/79b9693b-cae0-4ec4-9254-edfd2885eaef)
![Image](https://github.com/user-attachments/assets/2976b583-fcc3-4ca4-aeb0-2f73ee71df27)

**Comment by jemnery** [comment]
I've tracked this to a bug in Justice Data (just a bit of malformed markup). I'll raise a PR on JD to fix this.

**Comment by jemnery** [comment]
This is because we're truncating descriptions which contain markup. This leads to malformed HTML, breaking other elements on the page. You can see it here:

![Image](https://github.com/user-attachments/assets/3b3120c2-dee7-4506-a787-aca7b92b705a)
