### ISSUE TITLE
Signpost Find MoJ data from CaDeT user guide and readme

### ISSUE THREAD

**Issue by murdo-moj** [ministryofjustice/find-moj-data#866]
https://user-guidance.analytical-platform.service.justice.gov.uk/tools/create-a-derived-table/

**Comment by LavMatt** [comment]
This might already be done - see https://user-guidance.analytical-platform.service.justice.gov.uk/tools/create-a-derived-table/what-data-is-on-create-a-derived-table/

**Comment by murdo-moj** [comment]
Link was broken https://github.com/moj-analytical-services/user-guidance/pull/455/files
