### ISSUE TITLE
Explainer on what CaDeT is in Find MoJ data, and broadly what data it contains

### ISSUE THREAD

**Issue by murdo-moj** [ministryofjustice/find-moj-data#868]
For users coming to the homepage with little understanding of what data FMD holds and wanting to browse, have some copy on the homepage(?) about what content is in CaDeT, and Justice Data. We can add to this overview when we onboard new data sources.

Currently we have knowledge about broadly what data is in Cadet which could be useful to browsers about the cloned datasets we hold and where they come from, register my data, the uploader etc. We should communicate this to users.

We have content decisions to make as to where this information is directed to users. Does it go on the homepage? does it go on individual table/database entries?

**Comment by murdo-moj** [comment]
@markjefferson-gov do you have a steer as to where this type of information would go? If this ticket is unclear, then contact the devs to understnd better what information we are conveying

**Comment by markjefferson-gov** [comment]
Hi @murdo-moj . I'd say it depends on why the user needs to know. There are probably several needs which could be met in different ways.

Users likely need to know what data the catalogue currently holds. It makes sense to provide this on the home page -  either directly, or as a link to more info e.g. in the user guide. (I'm not sure how much there is to say currently but if you have a rough idea of what this needs to say, I could help you figure out where to put it.)

I'm not sure how useful this info is on its own. It helps users get a sense of the catalogue's scale and it might be useful if the user has a specific source in mind but it also reveals a weakness: we don't currently show users where specific data sets come from.

So once you introduce this info, users are likely to want to know what data from each source the catalogue currently holds. I think this needs to be shown on individual entries. I don't know what this means for CaDeT entries, though. You might need to show that it comes from CaDeT AND where CaDeT got it from. It might also be useful to show the sources in search results.

And if we think users have a specific interest in data from certain sources, we would need to address findability e.g. through browsing and/or search filters. 

Does this help?

**Comment by murdo-moj** [comment]
> we don't currently show users where specific data sets come from.

We have a [somewhat related ticket](https://github.com/ministryofjustice/find-moj-data/issues/867) which would involve marking individual entries with where they were ingested from, which would help to mitigate that weakness.

Here's some copy which might help:

Find MoJ data ingests metadata from various sources:

- [Create A Derived Table](https://github.com/moj-analytical-services/create-a-derived-table) is the main service to schedule derivations of data on the Analytical Platform (AP). Data modelling and engineering (DMET) curate analysis-ready clones of external databases using this service including:
    - Book A Secure Move
    - Caseman
    - Delius
    - Nomis
    - Oasys
    - Sirius
    - Xhibit
   Create A Derived Table also processes prison apps data and some tables uploaded from the [data uploader](https://user-guidance.analytical-platform.service.justice.gov.uk/tools/data-uploader/).
- Justice data is published stats data from https://data.justice.gov.uk/

**Comment by murdo-moj** [comment]
https://github.com/ministryofjustice/find-moj-data-user-guide/pull/24

**Comment by murdo-moj** [comment]
I've added that copy to the base page of the user guide for now.

**Comment by LavMatt** [comment]
have reached out in data-modelling slack channel for some additional input to this
