### ISSUE TITLE
Accessibility: change the description heading to H2

### ISSUE THREAD

**Issue by markjefferson-gov** [ministryofjustice/find-moj-data#881]
An issue was highlighted in the [basic accessibility check](https://docs.google.com/spreadsheets/d/1MqZJFOHzdpo1KpNuWi3gDTxqmLv27NT90kxOBzLBrY0/edit?usp=sharing) with the "Description" heading on data pages.

This is currently tagged as H3 and should be updated to H2.

**Comment by murdo-moj** [comment]
https://github.com/ministryofjustice/find-moj-data/pull/888
