### ISSUE TITLE
📚 First draft of source system database documentation

### ISSUE THREAD

**Issue by MatMoore** [ministryofjustice/find-moj-data#884]
### User Story

As a data consumer
When I browse to a database for a system
I need to understand what it is and how to use the data at a high level

### Proposal

After ingesting curated tables for each of the source systems, we want to populate the database level metadata, especially the description and subject area.

It's difficult to get access to the people that really know about these systems, so we should do a first draft ourselves, based on existing information, e.g. from data discovery tool (and the glue catalogue?)

After that, we can hand over to the data modellers.

### Definition of Done

- [x] Each source system database (nomis, delius etc) has a description
- [x] Each source system database has an assigned subject area

**Comment by murdo-moj** [comment]
https://data-discovery-tool.analytical-platform.service.justice.gov.uk/

**Comment by LavMatt** [comment]
guide for adding database metadata https://user-guide.find-moj-data.service.justice.gov.uk/data/cadet-db-registration/

**Comment by MatMoore** [comment]
Source for data discovery tool here: https://github.com/moj-analytical-services/data-discovery/tree/master/contributions

**Comment by MatMoore** [comment]
Some suggested descriptions below. The data discovery tool contains a lot of useful info about how datasets from these 3 systems can be linked, but based on prior discussions I don't think the catalogue can handle this kind of information at the moment.

## Offender Assessment System (OASys)
A snapshot of the operational OASys database. OASys is used by the prison and probation services to assess risks and needs of service users in custody and in the community, e.g. Risk of Serious Harm (RoSH) and Spousal Assault Risk Assessment (SARA).

## National Delius (Delius)
A snapshot of the operational National Delius database. National Delius (or NDelius, Delius) is the main case management system that records information about offenders on Probation, or in the community.

## Prison National Offender Management Information System (NOMIS)
A snapshot of the operational NOMIS database. NOMIS is the system used in prisons to manage information about offenders.

It contains offenders' personal details, age group, type of offence(s), type of custody (including those remanded on bail and sentenced), sentence length, prisoner movement data (internal and external), case note information, addresses of the prisoner (release, reception and curfew) and involvement in breaches of prison discipline. It also includes full details of the prisoners’ visits history, activities (both paid/unpaid work and offender rehabilitation programmes) and details of the prisoners’ financial records whilst in prison.

(second para reused from https://www.data.gov.uk/dataset/7237e18e-c1fe-443f-881a-1113b90b3351/prison-national-offender-management-information-system-p-nomis-and-inmate-information-system-iis)

**Comment by MatMoore** [comment]
https://github.com/moj-analytical-services/create-a-derived-table/pull/2166

**Comment by MatMoore** [comment]
Caseman & Book a secure move, sirius have not picked up the documentation yet

**Comment by LavMatt** [comment]
Issue with ingestion has been fixed so will appear on prod during next ingestion

Also added nomis sensitive so this can be closed
