### ISSUE TITLE
Activate HTTP compression in FMD app

### ISSUE THREAD

**Issue by jemnery** [ministryofjustice/find-moj-data#907]
Cloud Platform do not support HTTP compression, so try enabling it in the app. 

We have a lot of potentially compressible content (text and repeated markup) so it may make a noticeable difference to our ~650K payload and therefore page load times, but measure the effect to see if it's worth the CPU overhead.

(From tech review 01/10/24)

**Comment by murdo-moj** [comment]
> Security researchers recently revealed that when compression techniques (including GZipMiddleware) are used on a website, the site may become exposed to a number of possible attacks. Before using GZipMiddleware on your site, you should consider very carefully whether you are subject to these attacks. If you’re in any doubt about whether you’re affected, you should avoid using GZipMiddleware. For more details, see the the BREACH paper (PDF) and breachattack.com.

https://docs.djangoproject.com/en/5.1/ref/middleware/#module-django.middleware.gzip

**Comment by murdo-moj** [comment]
Django's middleware for Gzip has a mitigation in place for the security risk called "Heal the Breach". However if compression doesn't give us a large advantage in terms of load times we should think about if we want to weaken our security posture by introducing it.
