### ISSUE TITLE
Add runbook page for search config

### ISSUE THREAD

**Issue by jemnery** [ministryofjustice/find-moj-data#908]
Capture @mitchdawson1982 's research in the runbooks. Most (or all) of this can be copied from #877

**Comment by jemnery** [comment]
Align this with search exploration spike

**Comment by murdo-moj** [comment]
https://github.com/ministryofjustice/find-moj-data-runbooks/pull/66 This was done a while ago. If the search spike changes serach behaviour it'll need an update.
