### ISSUE TITLE
Enable Users to Report Issues with the metadata

### ISSUE THREAD

**Issue by teeceeas** [ministryofjustice/find-moj-data#911]
As a data catalogue user
I want a clear and easy way to report issues related to the data (e.g., broken links, incorrect contact details)
So that I can quickly alert the team about problems and help ensure the data catalog remains accurate and reliable.

**Acceptance Criteria:**
- A "Report an Issue" button/link is displayed prominently next to data contact information fields (request access, ask a question, data owner).
- The button/link is consistently placed on all dataset pages.
- When the "Report an Issue" button is clicked, a form should appear allowing users to select the type of issue (e.g., broken link, incorrect owner, outdated contact) or allow the user to provide the issue details.
- The form should have a free-text field where users can provide additional details about the issue.
- The form must include fields to collect the user’s contact details (optional) for follow-up if necessary.
- The form automatically pre-fills with the relevant dataset information (e.g., dataset name, current contact details) to reduce user effort and improve the accuracy of issue reporting.
- After submitting the issue, the user should see a confirmation message stating that their report has been sent.
- An automated notification is sent to the relevant dataset owner (if this exists), request originator, the data catalogue team when an issue is reported, including the dataset name, issue type, and user-provided details.

**Comment by jemnery** [comment]
We could borrow from this design, adapting the language

![Image](https://github.com/user-attachments/assets/fc30c301-7ac1-43b1-89f1-e3e5c88f89ae)

**Comment by jemnery** [comment]
If we want to use [GOV.UK Notify](https://www.notifications.service.gov.uk/services/c7a2ad47-e115-4652-b50a-cf05abdc88b8) I've created a placeholder template which can be edited as needed. 

https://www.notifications.service.gov.uk/services/c7a2ad47-e115-4652-b50a-cf05abdc88b8/templates/cc802e26-d308-433b-b523-40ff6a62f8c8

Template ID `cc802e26-d308-433b-b523-40ff6a62f8c8`

**Comment by jemnery** [comment]
[GOV.UK Notify](https://www.notifications.service.gov.uk/services/c7a2ad47-e115-4652-b50a-cf05abdc88b8) template which can be used to send to the **issue reporter**

https://www.notifications.service.gov.uk/services/c7a2ad47-e115-4652-b50a-cf05abdc88b8/templates/faf487a0-4d2e-4b9e-a22d-6322f7f7217c

Template ID `faf487a0-4d2e-4b9e-a22d-6322f7f7217c`

![Image](https://github.com/user-attachments/assets/a63defca-f0d4-4bae-bcd8-ad5bf486b668)

**Comment by mitchdawson1982** [comment]
- Notify API keys for testing and live have been added to github & 1password as env secrets as `NOTIFY_API_KEY`

**Comment by mitchdawson1982** [comment]
We have found an issue with the notify service where by urls ending with `)`are incorrectly rendered. We have opened an issue and are currently awaiting an ETA on a fix.
