### ISSUE TITLE
🐛 Duplicate ul ids in the search results  (was "subject area list")

### ISSUE THREAD

**Issue by murdo-moj** [ministryofjustice/find-moj-data#916]
The `<ul>` elements in search results repeat with the same id - `metadata-property-list`

![Image](https://github.com/user-attachments/assets/59bba11a-475f-4006-a703-dd7571dc0540)

**Comment by YvanMOJdigital** [comment]
https://docs.google.com/document/d/1XPEyiE7aIz0gqQ1ftnWgxK_2lSp2WG9M_z5f9RsaT18/edit#heading=h.4mtfxp8cgkh3
