### ISSUE TITLE
Remove search max length (was "Set something to show a maximum input length for search")

### ISSUE THREAD

**Issue by murdo-moj** [ministryofjustice/find-moj-data#917]
Remove `maxlength="100"` from the search input (search page not home page)

---

Min/max length on input boxes
It is best to avoid this as front-end validation as it can be easily changed. Best to keep as back end validation, which may already exist. For maxlength, once you reach 100+ characters, the fact that the input has stopped taking any more input is not communicated to the user, so it is dependent on the user seeing this happen and it is likely that the user will not realise.

**Comment by YvanMOJdigital** [comment]
https://docs.google.com/document/d/1XPEyiE7aIz0gqQ1ftnWgxK_2lSp2WG9M_z5f9RsaT18/edit#heading=h.4mtfxp8cgkh3

**Comment by YvanMOJdigital** [comment]
see moj design system

**Comment by mitchdawson1982** [comment]
- [Design System text input](https://design-system.service.gov.uk/components/text-input/)
- [Character count](https://design-system.service.gov.uk/components/character-count/)
