### ISSUE TITLE
🐛 Slack alert buttons don't work properly

### ISSUE THREAD

**Issue by MatMoore** [ministryofjustice/find-moj-data#932]
### Describe the bug.

Alertmanager alerts appear in slack with 4 buttons: Runbook, Query, Dashboard, Silence.

The Runbook and Dashboard buttons should help us to resolve the issue being alerted on, but the runbook one is a dead link.

The dashboard button is available for some of the alerts, but not all of them, so this might need reviewing as well.

### To Reproduce

Go to #data-catalogue-alerts channel and find an old alert (behaviour may differ depending on namespace, so check Find MoJ data and datahub in each environment)

### Expected Behaviour

The runbook link should take you to a dedicated page in the runbook for that alert, that explains what the alert means / what the person on support should do if this alert is firing. E.g. are there particular logs / events we need to look at?

The dashboard should show some additional information that is useful for debugging or understanding impact to users.

**Comment by murdo-moj** [comment]
https://github.com/ministryofjustice/cloud-platform-environments/pull/26897
https://github.com/ministryofjustice/cloud-platform-environments/pull/26898
https://github.com/ministryofjustice/cloud-platform-environments/pull/26902
https://github.com/ministryofjustice/cloud-platform-environments/pull/26903
