### ISSUE TITLE
Make it easier to notice production alerts

### ISSUE THREAD

**Issue by MatMoore** [ministryofjustice/find-moj-data#933]
### User Story

As the engineer on support
I need production alerts to be easily noticeable
So that I can respond quickly to problems

At the moment production/non-production alerts go to the same channel, and they are not visually distinguishable.

For example, the below screenshot shows 2 alerts, one which is affecting prod, the other which is affecting dev. Spot the difference...
![Image](https://github.com/user-attachments/assets/5a31dcc2-c6d6-4cbf-b224-3a4384e5eaa6)

The "live" label is a red herring, as this refers to the cloud platform cluster name, not our environment.

### Value / Purpose

This is a follow on ticket from https://github.com/ministryofjustice/find-moj-data/issues/832

Even after removing some of the false positives, it is currently very easy to miss alerts on prod, because we send non-prod alerts to the same channel, and don't distinguish them.

Solving this will improve our ability to respond more quickly to incidents.

### Hypothesis

If we make the important alerts easier to notice, we will act on them faster

### Proposal

A couple of options:

- Send non-prod alerts to a different channel
- Clearly mark the environment in the title of the alert

**Comment by murdo-moj** [comment]
Raised https://github.com/ministryofjustice/cloud-platform/issues/6294 to add a pingdom integration for prod only

**Comment by murdo-moj** [comment]
Also raised a support request with CP to change the Alertmanager alerts from Prometheus https://github.com/ministryofjustice/cloud-platform/issues/6300

**Comment by murdo-moj** [comment]
I have separated out our Sentry alert rules into environments so we can direct prod alerts to the new channel 

https://ministryofjustice.sentry.io/projects/find-moj-data/?project=4507181591101440
https://ministryofjustice.sentry.io/alerts/rules/?environment=prod&statsPeriod=14d
