### ISSUE TITLE
🔌 Connect Analytical Platform's Quicksight to Datahub's DB

### ISSUE THREAD

**Issue by MatMoore** [ministryofjustice/find-moj-data#965]
### User Story

We need a way of getting metadata into Quicksight so that we can report on metadata completeness.

We think the easiest way of doing that is via a direct database connection from Quicksight. See previous spike: https://github.com/ministryofjustice/find-moj-data/issues/910. (The alternative is to write a script to export data to an S3 bucket, but that would increase complexity and development time.) 

This ticket just covers the initial setup, not the creation of the dashboard.

### Useful Contacts

Julia, Darren, Jacob W (AP team), Mat (regarding the spike)

### Proposal

- Make sure AP team have capacity to help out with this before we start the sprint
- <strike>(Optional, to be discussed first) Set up a read replica for the datahub DB. ([Example terraform](https://github.com/ministryofjustice/cloud-platform-environments/blob/b51314640a4413b95b8f3837131b1df44d2aba64/namespaces/live.cloud-platform.service.justice.gov.uk/laa-assess-crime-forms-dev/resources/rds-postgresql.tf#L41))</strike> use pre-prod instead
- Create read-only database credentials
- Work with AP team to amend routing and security groups so that Quicksight can talk to the db (See [slack thread on connecting AP and MP](https://mojdt.slack.com/archives/C01A7QK5VM1/p1729173683976779))
- Make sure all Data Catalogue engineers can access Quicksight
- Add the data source within Quicksight

### Definition of Done

- [ ] Datahub data source is added to quicksight
- [ ] We can run queries within quicksight without errors

**Comment by MatMoore** [comment]
Thinking about it, the read only credentials may be fiddly to manage since this database schema isn't managed by us directly. Maybe we can just stick a credential in secrets manager and then manually create the user through SQL.

To set up a read only user we would need to run something like this:

```sql
CREATE USER xxx WITH PASSWORD yyy
GRANT CONNECT ON DATABASE mydb TO xxx;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO xxx;
```

**Comment by MatMoore** [comment]
This ticket is blocked on this AP one: https://github.com/ministryofjustice/analytical-platform/issues/5736
Which is currently blocked on this one: https://github.com/ministryofjustice/modernisation-platform/issues/7313

**Comment by LavMatt** [comment]
currently blocked because of an issue raised here with AP https://github.com/ministryofjustice/analytical-platform/issues/6094
