### ISSUE TITLE
Team!!:🔢 MVP metadata completeness dashboard

### ISSUE THREAD

**Issue by MatMoore** [ministryofjustice/find-moj-data#966]
**Do this first:** https://github.com/ministryofjustice/find-moj-data/issues/965

### User Story

As a data custodian
I want to be able to identify datasets with missing metadata
So that I can improve the metadata quality of my data

### Value / Purpose

This helps data custodians to improve the metadata, which increases the usefulness of the catalogue to end users.

Some fields are more critical than others (from a catalogue user perspective), such as ownership information and descriptions. 

### Out of scope for the first iteration

- Calculating an overall metadata score, taking into account all critical fields
- Aggregated completeness information (e.g. completeness by container, completeness by subject area etc.)

### Useful Contacts

Mat

### Hypothesis

If we create this dashboard
Then governance users will start using it
And we will start improving metadata already on the catalogue

### Proposal

Start out by focusing on data custodian, subject area and descriptions.

- Without data custodian info we have no accountability and reporting on the other metadata items is unlikely to get us anywhere.
- Subject area is important as it helps users find data that is relevant to them.
- Description is important as it helps users decide whether the data they have found is relevant or not.

We can start by creating a dashboard containing a table visualisation that
- Displays all the critical fields for each entity displayed in Find MoJ data
- Includes a boolean (integer in quicksight) field for each critical field, that indicates if the metadata is incomplete
- Includes the names of parent entities (e.g. container / dashboard / table)
- Filters out anything that is already 100% complete for all critical fields.

Once that is working, add a parameter/control to filter by container/dashboard name. Filtering on this should include the container/dashboard itself, and all entities that belong to it (such as tables, charts, columns)

The steps are:
1. [Define a parameter](https://docs.aws.amazon.com/quicksight/latest/user/parameters-in-quicksight.html)
2. [Define a control for the parameter](https://docs.aws.amazon.com/quicksight/latest/user/parameters-controls.html)
3. [Use the parameter in a filter](https://docs.aws.amazon.com/quicksight/latest/user/parameters-filtering-by.html)

### Additional Information (may or may not be useful)
Ideas from the [previous spike ticket](https://github.com/ministryofjustice/find-moj-data/issues/910):

- [Metadata completeness framework](https://docs.google.com/spreadsheets/d/1wqSFTp2_BrDxDuS7dfH6TdLmgv1GWvovy7kn0lEpjWc/edit?gid=0#gid=0)
- [Options for shaping the data](https://github.com/ministryofjustice/find-moj-data/issues/910#issuecomment-2416262149)
- [Visualisation options](https://github.com/ministryofjustice/find-moj-data/issues/910#issuecomment-2426154491)

In case any of this is reusable, here is a rough query I used for testing, which selects various aspects of Dataset entities, filters out non-current ones, extracts some relevant fields from the metadata JSON, then joins everything together:

```sql
WITH schemaMetadata AS (
	SELECT urn, version
	FROM metadata_aspect_v2
	WHERE aspect='schemaMetadata'
	AND NOT EXISTS(
		SELECT 1 FROM metadata_aspect_v2 other
		WHERE other.urn = metadata_aspect_v2.urn
		AND other.aspect='schemaMetadata'
		AND other.version > metadata_aspect_v2.version
	)
),

datasetProperties AS (
	SELECT urn, version, metadata::json->>'name' AS name,
	metadata::json->>'description' AS description,
	metadata::json->>'displayName' AS display_name
	FROM metadata_aspect_v2
	WHERE aspect='datasetProperties'
	AND NOT EXISTS(
		SELECT 1 FROM metadata_aspect_v2 other
		WHERE other.urn = metadata_aspect_v2.urn
		AND other.aspect='datasetProperties'
		AND other.version > metadata_aspect_v2.version
	)
),

container AS (
	SELECT urn, version, metadata::json->>'container' as containerUrn
	FROM metadata_aspect_v2
	WHERE aspect='container'
	AND NOT EXISTS(
		SELECT 1 FROM metadata_aspect_v2 other
		WHERE other.urn = metadata_aspect_v2.urn
		AND other.aspect='container'
		AND other.version > metadata_aspect_v2.version
	)
),

domain AS (
	SELECT urn, version, metadata::json->>'domain' as domainUrn
	FROM metadata_aspect_v2
	WHERE aspect='domain'
	AND NOT EXISTS(
		SELECT 1 FROM metadata_aspect_v2 other
		WHERE other.urn = metadata_aspect_v2.urn
		AND other.aspect='domain'
		AND other.version > metadata_aspect_v2.version
	)
)


SELECT
  datasetProperties.*,
  schemaMetadata.urn is not null as hasSchema,
  container.containerUrn,
  domain.domainUrn
from datasetProperties
left join schemaMetadata using(urn)
left join container using(urn)
left join domain using(urn)
```

@LavMatt also added a similar query in this notebook: https://github.com/ministryofjustice/data-catalogue/blob/main/datahub_metrics/metadata_metric_charts.ipynb

### Definition of Done

- [ ] We have a dashboard
- [ ] We can view entities with incomplete metadata
- [ ] We can filter by container or dashboard name
- [ ] Tickets created for any suggested improvements to the dashboard content (e.g. additional panels)

**Comment by murdo-moj** [comment]
```
WITH schemaMetadata AS (
	SELECT urn, version
	FROM metadata_aspect_v2
	WHERE aspect='schemaMetadata'
	AND NOT EXISTS(
		SELECT 1 FROM metadata_aspect_v2 other
		WHERE other.urn = metadata_aspect_v2.urn
		AND other.aspect='schemaMetadata'
		AND other.version > metadata_aspect_v2.version
	)
),

datasetProperties AS (
	SELECT urn, version, metadata::json->>'name' AS name,
	metadata::json->>'description' AS description,
	metadata::json->>'displayName' AS display_name
	FROM metadata_aspect_v2
	WHERE aspect='datasetProperties'
	AND NOT EXISTS(
		SELECT 1 FROM metadata_aspect_v2 other
		WHERE other.urn = metadata_aspect_v2.urn
		AND other.aspect='datasetProperties'
		AND other.version > metadata_aspect_v2.version
	)
),

container AS (
	SELECT urn, version, metadata::json->>'container' as containerUrn
	FROM metadata_aspect_v2
	WHERE aspect='container'
	AND NOT EXISTS(
		SELECT 1 FROM metadata_aspect_v2 other
		WHERE other.urn = metadata_aspect_v2.urn
		AND other.aspect='container'
		AND other.version > metadata_aspect_v2.version
	)
),

domain AS (
	SELECT urn, version, metadata::json->>'domain' as domainUrn
	FROM metadata_aspect_v2
	WHERE aspect='domain'
	AND NOT EXISTS(
		SELECT 1 FROM metadata_aspect_v2 other
		WHERE other.urn = metadata_aspect_v2.urn
		AND other.aspect='domain'
		AND other.version > metadata_aspect_v2.version
	)
),


custodians AS (
    SELECT urn, metadata::json->'owners'->0->>'owner' AS custodianUrn
    FROM metadata_aspect_v2
    WHERE aspect='ownership'
	AND NOT EXISTS(
		SELECT 1 FROM metadata_aspect_v2 other
		WHERE other.urn = metadata_aspect_v2.urn
		AND other.aspect='ownership'
		AND other.version > metadata_aspect_v2.version
	)
)


SELECT
  datasetProperties.*,
  schemaMetadata.urn is not null as hasSchema,
  datasetProperties.description is not null as hasDescription,
  domain.domainUrn is not null as hasDomain,
  custodians.custodianUrn is not null as hasCustodian,
  container.containerUrn,
  domain.domainUrn,
  custodians.custodianUrn
from datasetProperties
left join schemaMetadata using(urn)
left join container using(urn)
left join domain using(urn)
left join custodians using(urn)
```

**Comment by murdo-moj** [comment]
```
SELECT (
	-- COUNT(DISTINCT urn), 
	urn
 ) FROM metadata_aspect_v2 
  WHERE aspect IN ('chartInfo', 'dashboardInfo', 'container', 'datasetProperties')
  AND metadata::json->>'tags' like '%dc_display_in_catalogue%'
```

**Comment by murdo-moj** [comment]
```
WITH datasets AS (
    select 
        urn,
        MIN(version) as latest
    FROM
        metadata_aspect_v2
    WHERE
        aspect in ('datasetProperties','chartInfo', 'containerProperties', 'dashboardInfo')
    GROUP BY
        urn
),

final AS (
SELECT
    datasets.urn,
    SUBSTRING(
        datasets.urn, 
        POSITION('urn:li:' IN datasets.urn) + LENGTH('urn:li:'),
        POSITION(':' IN SUBSTRING(datasets.urn FROM POSITION('urn:li:' IN datasets.urn) + LENGTH('urn:li:'))) - 1
    ) AS entity_type,
    properties.metadata::json ->> 'description' as description,
    properties.metadata::json -> 'customProperties' ->> 'dc_slack_channel_name' as slack_channel_name,
    properties.metadata::json -> 'customProperties' ->> 'dc_slack_channel_url' as slack_channel_url,
    properties.metadata::json -> 'customProperties' ->> 'dc_access_requirements' as access_requirements,
    properties.metadata::json -> 'customProperties' ->> 'refresh_period' as refresh_period,
    ownership.metadata::json -> 'owners' -> 0 ->> 'owner' as owner,
    domains.metadata::json -> 'domains' ->> 0 as domain
FROM
    datasets
LEFT JOIN metadata_aspect_v2 as properties
    ON (properties.urn=datasets.urn and properties.aspect in ('datasetProperties','chartInfo', 'containerProperties', 'dashboardInfo') 
        and properties.version=datasets.latest)
LEFT JOIN metadata_aspect_v2 as ownership 
    ON (ownership.urn=datasets.urn and ownership.aspect = 'ownership' and ownership.version=0)
LEFT JOIN metadata_aspect_v2 as tags
    ON (datasets.urn=tags.urn and tags.aspect = 'globalTags' and tags.version=0)
LEFT JOIN metadata_aspect_v2 as domains
    ON (datasets.urn=domains.urn and domains.aspect = 'domains' and domains.version=0)
WHERE EXISTS (
    SELECT 1
    FROM jsonb_array_elements(tags.metadata::jsonb->'tags') AS tag_element
    WHERE tag_element->>'tag' = 'urn:li:tag:dc_display_in_catalogue'
)
ORDER BY datasets.urn
)

SELECT *,
    (owner = '') is FALSE as has_owner,
    (description = '') is FALSE as has_description,
    (slack_channel_url = '') is FALSE as has_slack_channel_url,
    (domain = '') is FALSE as has_domain
FROM final
```

**Comment by murdo-moj** [comment]
[Ticket to get Tochi access to Quicksight](https://github.com/ministryofjustice/analytical-platform/issues/6155)

**Comment by murdo-moj** [comment]
This can go in done when Tochi has quicksight access
