### ISSUE TITLE
Add more metadata properties to catalogue items (Justice Data)

### ISSUE THREAD

**Issue by teeceeas** [ministryofjustice/find-moj-data#989]
As a user of Find MoJ data, I want additional metadata properties displayed for each dataset, so that I have access to more metadata to better understand the dataset

**Acceptance Criteria:**

**Date Modified**
- A new field "Date Modified" is added to datasets
- Displays the date (or date and time) when the content of the resource was last changed.

**Provider/Source**
- A new field "Provider/Source" is added to datasets
- Displays the source or provider name (e.g., CaDeT, Justice Data, NOMIS).

**Last Updated**
- A new field "Last Updated" is added to datasets
- Displays the date when the data itself was last updated, as opposed to metadata changes.

**Update Frequency**
- A new field "Update Frequency" is added to datasets
- Specifies the expected interval for data updates (e.g., daily, weekly, monthly, yearly).

**Audience**
- A new field "Audience" is added to datasets
- Specifies whether the resource is intended for "Internal" or "Published" audiences.

Add glossary entry for the definitions of each item

**Comment by MatMoore** [comment]
The charts themselves do not have timeliness metadata, but we can derive the dates from the publication API https://data.justice.gov.uk/api/publications

Proposed metadata:

- Date modified (metadata) - `currentPublishDate` (TBC)
- Provider - hardcode to `Justice Data` (TBC)
- Last updated (data) - `currentPublishDate`
- Update frequency - `frequency`
- Audience - hardcode to `Published`
